GoogleCloudPlatform/iap-desktop

Plugin.Google.CloudIap/Gui/Plugin.cs
Plugin.Google.CloudIap/Gui/SerialPortOutputWindow.Designer.cs
Plugin.Google.CloudIap/Gui/TunnelsWindow.Designer.cs
Plugin.Google.CloudIap/Gui/TunnelsWindow.cs
Plugin.Google.CloudIap/Gui/TunnelsWindow.resx
Plugin.Google.CloudIap/Integration/GcloudProcess.cs
Plugin.Google.CloudIap/Integration/IapTunnelManager.cs
Plugin.Google.CloudIap/Plugin.Google.CloudIap.csproj

Add a **Tools > Tunnels** window to view open tunnels and allowing terminating tunnels.

Add tunnels window for viewing and terminating open tunnels

---

Plugin.Google.CloudIap/Gui/Plugin.cs

* Add 'Connect server via Cloud IAP as...' command to menu to connect as different user
* Support virtual groups in server tree

Add 'Connect server via Cloud IAP as...' command 

---

kokoro/nunit-to-sponge.xsl

Fix XSLT to produce Sponge-compliant XML so that the test results can be browsed in TestFusion

Convert Nunit3 test results into Sponge-compatible format.

---

Google.Solutions.CloudIap.Plugin/Gui/ExceptionUtil.cs
Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs
Google.Solutions.CloudIap.Plugin/Gui/SerialPortOutputWindow.cs
Google.Solutions.CloudIap.Plugin/Gui/WaitDialog.cs
Google.Solutions.CloudIap.Plugin/Integration/DefaultTunnelingManager.cs
Google.Solutions.CloudIap.Plugin/Integration/GcloudTunnelManager.cs
Google.Solutions.CloudIap.Plugin/Integration/TunnelManagerBase.cs
Google.Solutions.Compute/Auth/Authorization.cs

Restart OAuth authorization code flow whenever an `invalid_grant` error occurs
* Open browser and request user to re-authorize
* Restart the failed operation using new credentials

Support OAuth reauth

---

Google.Solutions.CloudIap.Plugin/Integration/ComputeEngineAdapter.cs

Old instances might not have a proper guest OS feature, fall back to filtering by license in this case.
This is to fix https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/issues/22

Filter Windows instances by license or guest feature

---

build.ps1

Change-Id: I0384a658a1f9ba4dc4d4ff651bb62c38a09635fc

Bump version to 1.1

---

Google.Solutions.CloudIap.Installer/Product.wxs

Fix issue where the LaunchCondition failed when
the same package version was being installed again.

Allow reinstalling same product version

---

Google.Solutions.CloudIap.sln
Google.Solutions.Compute.Test/Env/ComputeEngine.cs
Google.Solutions.Compute.Test/Env/Defaults.cs
Google.Solutions.Compute.Test/Extensions/TestResetWindowsUser.cs
Google.Solutions.Compute.Test/Iap/TestEchoOverIapDirectTunnel.cs
Google.Solutions.Compute.Test/Iap/TestEchoOverIapIndirectTunnel.cs
Google.Solutions.Compute.Test/Iap/TestHttpOverIapDirectTunnel.cs
Google.Solutions.Compute.Test/Iap/TestHttpOverIapIndirectTunnel.cs
Google.Solutions.Compute.Test/Iap/TestSshRelayProber.cs
build.ps1
kokoro/continuous.cfg
kokoro/presubmit.cfg

Run all tests except for those that use IAP with WebSockets (so that it is Win2012 compatible)

Run integration tests

---

Google.Solutions.CloudIap.Installer/Product.wxs
Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs

Add workaround for RDCMab's buggy WM_KILLFOCUS handling

---

Google.Solutions.CloudIap.Installer/Product.wxs

Change-Id: I9c5d67d5982bc74ba38e4fb436830ef6bd9a20c9

Add Google.Apis.CloudResourceManager.v1.dll to MSI

---

Google.Solutions.CloudIap.Plugin/Configuration/PluginConfiguration.cs
Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs

Change-Id: I5211d24de6f6935eda32c465535285d4fe44649b

Force token refresh before opening Add Project dialog

---

Google.Solutions.Compute/Extensions/ResetWindowsUser.cs

Sometimes, the result can be split and returned in two
subsequent calls. Use a buffer to support this situation
properly.

Maintain buffer for reading password reset result

---

Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs
Google.Solutions.CloudIap.Plugin/Gui/WaitDialog.Designer.cs
Google.Solutions.CloudIap.Plugin/Gui/WaitDialog.cs
Google.Solutions.CloudIap.Plugin/Integration/ComputeEngineAdapter.cs
Google.Solutions.CloudIap.Plugin/Integration/GcloudTunnelManager.cs
Google.Solutions.CloudIap.Plugin/Integration/TunnelManagerBase.cs
Google.Solutions.Compute.Test/Extensions/TestResetWindowsUser.cs
Google.Solutions.Compute.Test/Google.Solutions.Compute.Test.csproj
Google.Solutions.Compute.Test/packages.config
Google.Solutions.Compute/Extensions/ResetWindowsUser.cs

Cancel background operation when user presses _Cancel_ in `WaitDialog`.

Cancel password reset when pressing 'Cancel'

---

Google.Solutions.CloudIap.Plugin/Configuration/PluginConfiguration.cs
Google.Solutions.CloudIap.Plugin/Google.Solutions.CloudIap.Plugin.csproj
Google.Solutions.CloudIap.Plugin/Gui/Plugin.cs
Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs
Google.Solutions.CloudIap.Plugin/Gui/UnsafeNativeMethods.cs
Google.Solutions.CloudIap.Plugin/Integration/GithubAdapter.cs
Google.Solutions.CloudIap.Plugin/Integration/RestClient.cs

* Add GithubAdapter to query for latest version
* Show TaskDialog on close, propting for update
* Show installed version in Settings dialog

Check for updates on close

---

Google.Solutions.CloudIap.Plugin/Configuration/PluginConfiguration.cs
Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs

* Store timestamp of last check as part of configuration
* Skip check if less than a week ago
* Display timestamp in settings dialog

Check for updates only once a week

---

Google.Solutions.CloudIap.Plugin/Configuration/PluginConfiguration.cs
Google.Solutions.Compute/Compute.cs
Google.Solutions.Compute/Extensions/AddMetadata.cs
Google.Solutions.Compute/Extensions/GetSerialPortOutputStream.cs
Google.Solutions.Compute/Extensions/ResetWindowsUser.cs

* Expose setting in Settings dialog
* Add tracing to extension commands

Enable diagnostic tracing

---

Google.Solutions.CloudIap.Plugin/Integration/ComputeEngineAdapter.cs
Google.Solutions.Compute.Test/Google.Solutions.Compute.Test.csproj
Google.Solutions.Compute.Test/TestLinqExtensions.cs

This PR is to fix https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/issues/53

Fix NRE caused by empty list of disks/OS features

---

Google.Solutions.IapDesktop.Application.Test/Windows/TestProjectExplorerNode.cs
Google.Solutions.IapDesktop.Application/Settings/InventorySettingsRepository.cs
Google.Solutions.IapDesktop.Application/Windows/RemoteDesktop/RdpExceptions.cs
Google.Solutions.IapDesktop.Application/Windows/RemoteDesktop/RemoteDesktopPane.Designer.cs
Google.Solutions.IapDesktop.Application/Windows/RemoteDesktop/RemoteDesktopPane.cs
Google.Solutions.IapDesktop.Application/Windows/RemoteDesktop/RemoteDesktopPane.resx
Google.Solutions.IapDesktop/Program.cs

* Add "AutoAdjust" setting for desktop size
* Automatically reconnect RDP to adjust desktop size to client size
* Adjust desktop size to screen size if in full screen mode

Auto-resize remote desktop to current client size

---

Google.Solutions.Compute.Test/Auth/TestAuthorization.cs
Google.Solutions.Compute.Test/Extensions/TestGetSerialPortOutputStream.cs
Google.Solutions.IapDesktop.Application.Test/TestExceptionExtensions.cs
build.ps1

* Add missing copyright headers
* Add check in `build.ps1` to fail build if headers are missing

Add missing copyright headers

---

Google.Solutions.Compute/Net/NetworkStream.cs
Google.Solutions.Compute/TraceSources.cs
Google.Solutions.IapDesktop.Application.Test/FixtureBase.cs
Google.Solutions.IapDesktop.Application.Test/Settings/TestInventorySettingsRepository.cs
Google.Solutions.IapDesktop.Application.Test/Windows/TestRemoteDesktop.cs
Google.Solutions.IapDesktop.Application.Test/Windows/TestRemoteDesktopGroupPolicies.cs
Google.Solutions.IapDesktop.Application.Test/Windows/TestRemoteDesktopOverIap.cs
Google.Solutions.IapDesktop.Application.Test/Windows/WindowTestFixtureBase.cs
Google.Solutions.IapDesktop.Application/Settings/InventorySettingsRepository.cs
Google.Solutions.IapDesktop.Application/Windows/ProjectExplorer/ProjectExplorerWindow.cs
Google.Solutions.IapDesktop.Application/Windows/RemoteDesktop/RemoteDesktopPane.cs

Change-Id: I82842c42de602e593b7b5bc11ea0890932bbc2d7

Apply timeout when waiting for event

---

build.ps1

Log Nunit to Stdout to avoid losing logs in case of a timeout

Log Nunit to Stdout

---

Google.Solutions.IapDesktop/Windows/MainForm.Designer.cs
Google.Solutions.IapDesktop/Windows/MainForm.resx

Show which keystrokes are sent to remote VM

Add keystroke to menu label

---

Google.Solutions.IapDesktop.Application/Services/UpdateService.cs
Google.Solutions.IapDesktop.Application/Windows/ProjectExplorer/ProjectExplorerWindow.cs

Check instance state before connecting via Enter/double-click

Fix NullReference when connecting to stopped VM

---

Google.Solutions.IapDesktop.Application.Test/Windows/TestRemoteDesktopGroupPolicies.cs
Google.Solutions.IapDesktop.Application.Test/Windows/WindowTestFixtureBase.cs
Google.Solutions.IapDesktop.Application/Windows/RemoteDesktop/RemoteDesktopPane.cs

Change-Id: Ie95b48af229e44dffd22cc1de381867f8a77d3e3

Add instrumentation to analyze test hangs

---

Google.Solutions.IapDesktop.Application.Test/Windows/WindowTestFixtureBase.cs

Change-Id: I319f179c266b8fa13c5657f33ea2231476dab09c

Avoid jamming test log with wait messages

---

.gitignore
Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
Google.Solutions.IapDesktop/packages.config
build.ps1
kokoro/presubmit.cfg

Change-Id: I4aeeffa659706b0ee64c9e96c9db6c0af83abb58

Integrate OpenCover into build

---

Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
Google.Solutions.IapDesktop.Application.Test/Util/TestSingletonApplicationBase.cs
Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
Google.Solutions.IapDesktop.Application/Services/Windows/ProjectExplorer/IProjectExplorer.cs
Google.Solutions.IapDesktop.Application/Services/Windows/ProjectExplorer/ProjectExplorerWindow.cs
Google.Solutions.IapDesktop.Application/Services/Workflows/RemoteDesktopConnectionService.cs
Google.Solutions.IapDesktop.Application/Util/SingletonApplicationBase.cs
Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
Google.Solutions.IapDesktop/Program.cs
Google.Solutions.IapDesktop/UnsafeNativeMethods.cs
Google.Solutions.IapDesktop/Windows/MainForm.cs

Run a single instance per app, channel arguments of subsequent invocations to the first instance.

Singleton behavior

---

Google.Solutions.Compute/Extensions/ResetWindowsUser.cs
Google.Solutions.IapDesktop.Application/Services/Windows/ExceptionDialog.cs

* Render GoogleApiExceptions in a more legible format
* Add more verbose tracing for password reset errors

Show additional information about API errors

---

build-installer.ps1
kokoro/continuous.cfg
kokoro/presubmit.cfg

Change-Id: I1928ef753ce31c39e286b6306ec016933cc30dd9

Create archive with debugging symbols

---

build.ps1

Change-Id: Icb350b9d429f481f588552e31330f2ca114701e5

(Re-) add firewall rule for IAP before test

---

Google.Solutions.Common.Test/ApiExtensions/Instance/TestAddMetadata.cs
Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
Google.Solutions.Common.Test/TestGlobalResourceReference.cs
Google.Solutions.Common.Test/TestZonalResourceReference.cs
Google.Solutions.Common/ZonalResourceReference.cs

* Add tests for resource reference classes 
* Add tests for AddMetadata

Increase test coverage in Common lib

---

Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
Google.Solutions.IapDesktop.Application.Test/ObjectModel/TestBindingExtensions.cs
Google.Solutions.IapDesktop.Application.Test/Util/TestRangeObservableCollection.cs
Google.Solutions.IapDesktop.Application/Controls/BindableListView.cs
Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
Google.Solutions.IapDesktop.Application/ObjectModel/BindingExtensions.cs
Google.Solutions.IapDesktop.Application/Util/RangeObservableCollection.cs

* Add RangeObservableCollection
* Apply initial value from model when binding …

Fixes for model binding

---

Google.Solutions.IapDesktop.Extensions.LogAnalysis.Test/Google.Solutions.IapDesktop.Extensions.LogAnalysis.Test.csproj
Google.Solutions.IapDesktop.Extensions.LogAnalysis.Test/History/TestAnnotatedInstanceSetHistory.cs
Google.Solutions.IapDesktop.Extensions.LogAnalysis.Test/History/TestLicenseLoader.cs
Google.Solutions.IapDesktop.Extensions.LogAnalysis/Google.Solutions.IapDesktop.Extensions.LogAnalysis.csproj
Google.Solutions.IapDesktop.Extensions.LogAnalysis/History/AnnotatedInstanceSetHistory.cs
Google.Solutions.IapDesktop.Extensions.LogAnalysis/History/ImageAnnotation.cs
Google.Solutions.IapDesktop.Extensions.LogAnalysis/History/LicenseLoader.cs

* Add AnnotatedInstanceSetHistory 
* Add ability to hydrate annotations from Images API

Track license annotations in instance history

---

Google.Solutions.Common/Diagnostics/TraceSourceLogger.cs

* Add TraceSourceLogger
* Enable logging along with other TraceSources

Enable logging of API calls

---

Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
Google.Solutions.Common.Test/Net/TestUserAgent.cs
Google.Solutions.Common.Test/Testbed/Defaults.cs
Google.Solutions.Common/Google.Solutions.Common.csproj
Google.Solutions.Common/Net/RestClient.cs
Google.Solutions.Common/Net/UserAgent.cs
Google.Solutions.IapDesktop.Application.Test/RdpTunnel.cs
Google.Solutions.IapDesktop.Application/Global.cs
Google.Solutions.IapDesktop.Application/Services/Adapters/ComputeEngineAdapter.cs
Google.Solutions.IapDesktop.Application/Services/Adapters/GithubAdapter.cs
Google.Solutions.IapDesktop.Application/Services/Adapters/ResourceManagerAdapter.cs
Google.Solutions.IapDesktop.Application/Services/Integration/TunnelService.cs
Google.Solutions.IapDesktop.Extensions.Activity/Services/Adapters/AuditLogAdapter.cs
Google.Solutions.IapDesktop/Program.cs
Google.Solutions.IapTunneling.Test/Google.Solutions.IapTunneling.Test.csproj
Google.Solutions.IapTunneling.Test/Iap/TestEchoOverIapIndirectTunnel.cs
Google.Solutions.IapTunneling.Test/Iap/TestHttpOverIapDirectTunnel.cs
Google.Solutions.IapTunneling.Test/Iap/TestHttpOverIapIndirectTunnel.cs
Google.Solutions.IapTunneling.Test/Iap/TestSshRelayProber.cs
Google.Solutions.IapTunneling.Test/Net/TestRestrictedHeaderConfigPatch.cs
Google.Solutions.IapTunneling/Google.Solutions.IapTunneling.csproj
Google.Solutions.IapTunneling/Iap/IapTunnelingEndpoint.cs
Google.Solutions.IapTunneling/Net/RestrictedHeaderConfigPatch.cs

Pass a custom User-Agent header to:
* IAP API
* Compute API
* Resource Manager API
* Logging API
* GitHub API

Pass custom User-Agent to APIs

---

Google.Solutions.Common/Diagnostics/SkipCodeCoverageAttribute.cs
Google.Solutions.Common/Google.Solutions.Common.csproj
Google.Solutions.IapDesktop.Application/Services/Windows/TunnelsViewer/TunnelsWindow.cs
Google.Solutions.IapDesktop.Extensions.Activity/Services/SchedulingReport/ReportPaneView.cs
build.ps1

Change-Id: I1124269e6da5dd896e233193b1d1242f4ce92789

Ignore view classes (as in MVVM) from code coverage

---

Google.Solutions.IapDesktop.Application/Services/Persistence/ApplicationSettingsRepository.cs
Google.Solutions.IapDesktop.Extensions.Activity/Services/Extension.cs
installer/Product.wxs

* Add files to installer
* Add feature flag to en/disable extension

Add Analysis extension to installer

---

Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
Google.Solutions.IapDesktop/app.manifest

This is to ensure Environment.OSVersion returns the actual
version.

Add application manifest

---

Google.Solutions.IapDesktop.Extensions.Activity.Test/Logs/TestLogRecord.cs
Google.Solutions.IapDesktop.Extensions.Activity/Events/Lifecycle/LifecycleEventBase.cs
Google.Solutions.IapDesktop.Extensions.Activity/Logs/LogRecord.cs

Change-Id: Icc419467a440be8d0a84ef4e789570682eb13796

Indicate operation start/end in event log

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/ObjectModel/TestCommandContainerForContextMenu.cs
sources/Google.Solutions.IapDesktop.Application.Test/ObjectModel/TestCommandContainerForToolbar.cs
sources/Google.Solutions.IapDesktop.Application/ObjectModel/CommandContainer.cs
sources/Google.Solutions.IapDesktop.Application/Services/Windows/HtmlPageGenerator.cs
sources/Google.Solutions.IapDesktop.Application/Services/Windows/ProjectExplorer/IProjectExplorer.cs
sources/Google.Solutions.IapDesktop.Application/Services/Windows/ProjectExplorer/ProjectExplorerWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Services/Extension.cs
sources/Google.Solutions.IapDesktop.Extensions.Os/Services/Extension.cs
sources/Google.Solutions.IapDesktop.Extensions.Os/Services/InstanceDetails/InstanceDetailsViewModel.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

Allow toolbat menu items to be registered using the same
approach as used for the context menu.

Dynamic toolbar menus

---

sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugDockingWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugDockingWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugDockingWindow.resx
sources/Google.Solutions.IapDesktop.Application/Views/ToolWindow.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Consider dock/auto-hide window visible even if it does not have focus
* Consider floating split-pane window visible

Improve reliability of visibility tracking

---

sources/Google.Solutions.IapDesktop.Extensions.Rdp/Views/Credentials/CredentialPrompt.cs

This is to prevent a reauth error when connecting to an
instance.

Catch reauth error when performing permission check

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/WindowTestFixtureBase.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/GithubAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Util/IapRdpUrl.cs
sources/Google.Solutions.IapDesktop.Application/Views/ExceptionDialog.cs
sources/Google.Solutions.IapDesktop.Application/Views/HelpService.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/GeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/UnsafeNativeMethods.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Services/Connection/IapRdpConnectionService.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Extend `ExceptionDdialog` to support showing links
* Add `IHelpTopic` interface
* Include help topic in common connection-related exceptions

b/170729971 Link to help in error messages

---

sources/Google.Solutions.IapDesktop.Application/Views/Properties/PropertiesInspectorWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Os/Services/Extension.cs
sources/Google.Solutions.IapDesktop.Extensions.Os/Views/InstanceProperties/InstancePropertiesInspectorModel.cs

Change order of property updates so that the window
title is properly updated.

Show proper title in Instance Properties window

---

sources/Google.Solutions.Common.Test/Util/TestExceptionExtensions.cs
sources/Google.Solutions.Common/Util/ExceptionExtensions.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestNetworkOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/HttpProxyAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Settings/ApplicationSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/NetworkOptionsControl.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/NetworkOptionsControl.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/NetworkOptionsViewModel.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Extend options dialog
* Extend ApplicationSettings to persist proxy credentials
* Extend HttpProxyAdapter to apply credentials

b/172045559 Add support for proxy authentication

---

sources/Google.Solutions.IapTunneling/Iap/SshRelayStream.cs

This prevents a TOCTOU condition where the code
tries to pull a message from an empty queue, causing
a NRE and a connection failure.

Lock access to the resend queue

---

sources/Google.Solutions.IapDesktop/Windows/MainForm.Designer.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

Signing out without existing provides little value,
thus combining the two actions.

Change menu to 'Sign out and exit'

---

sources/Google.Solutions.IapDesktop.Application/Views/CloudConsoleService.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerNode.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs

Show _Open in Cloud Console_ and _Configure IAP access_ commands for project,
zone, and VM instance nodes.

b/175091653 Show cloud console commands for project, zone, VM

---

sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/InstanceUtil.cs
sources/Google.Solutions.Ssh.Test/Native/TestSession.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshAuthenticatedSession.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshConnectedSession.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshExecChannel.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshShellChannel.cs
sources/Google.Solutions.Ssh.Test/SshAssert.cs
sources/Google.Solutions.Ssh.Test/TestSshShellConnection.cs
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/ISshKey.cs
sources/Google.Solutions.Ssh/Native/Disposable.cs
sources/Google.Solutions.Ssh/Native/SshAuthenticatedSession.cs
sources/Google.Solutions.Ssh/Native/SshChannelBase.cs
sources/Google.Solutions.Ssh/Native/SshConnectedSession.cs
sources/Google.Solutions.Ssh/Native/SshException.cs
sources/Google.Solutions.Ssh/Native/SshSession.cs
sources/Google.Solutions.Ssh/Native/SshSessionChannelBase.cs
sources/Google.Solutions.Ssh/Native/UnsafeNativeMethods.cs
sources/Google.Solutions.Ssh/RsaSshKey.cs
sources/Google.Solutions.Ssh/SshConnectionBase.cs
sources/Google.Solutions.Ssh/SshShellConnection.cs
sources/Google.Solutions.Ssh/SshWorkerThread.cs
sources/Google.Solutions.Ssh/TerminalSize.cs

* Remove all Task wrappers
* Refactor SshShellConnection to use a single thread
* Use non-blocking I/O with WSAEventSelect and
WSAWaitForMultipleObjectsto operate
* Add ISshKey interface

Use non-blocking I/O

---

sources/Google.Solutions.IapDesktop.Extensions.Rdp.Test/Services/Connection/TestIapRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Services/Connection/IapRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Services/Extension.cs

* Add 'Connect as user' command
* Extend IapRdpConnectionService to optionally skip logic for persistent credentials
* Add test

b/177056284 Connect as different user

---

sources/Google.Solutions.IapDesktop.Extensions.Rdp/Views/RemoteDesktop/RemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh/GlobalSuppressions.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh/Services/Auth/AuthorizedKeyService.cs
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/Native/TestEnvironmentVariable.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshShellChannel.cs
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/Native/EnvironmentVariable.cs
sources/Google.Solutions.Ssh/Native/SshAuthenticatedSession.cs
sources/Google.Solutions.Ssh/Native/SshSession.cs
sources/Google.Solutions.Ssh/SshConnectionBase.cs
sources/Google.Solutions.Ssh/SshShellConnection.cs

* Remove obsolete TODO comments
* Restrict visibility
* Fix code analysis nits

Code cleanup

---

sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/TestStreamingDecoder.cs
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/SshConnectionBase.cs
sources/Google.Solutions.Ssh/SshShellConnection.cs
sources/Google.Solutions.Ssh/StreamingDecoder.cs

Handle UTF-8 sequences when split over multiple receive operations

b/178082883 Handle partial UTF-8 sequences

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Services/Integration/TestSessionBroker.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/TestProjectExplorer.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/WindowTestFixtureBase.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Services/Integration/SessionBroker.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp.Test/Google.Solutions.IapDesktop.Extensions.Rdp.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Rdp.Test/Services/Connection/TestIapRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp.Test/Views/RemoteDesktop/TestRemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp.Test/Views/RemoteDesktop/TestRemoteDesktopPaneWithGroupPolicies.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp.Test/Views/RemoteDesktop/TestRemoteDesktopSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Google.Solutions.IapDesktop.Extensions.Rdp.csproj
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Services/Connection/IapRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Services/Extension.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Views/RemoteDesktop/RemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Rdp/Views/RemoteDesktop/RemoteDesktopSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh.Test/Google.Solutions.IapDesktop.Extensions.Ssh.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Ssh.Test/Views/Terminal/TestSshTerminalPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh.Test/Views/Terminal/TestSshTerminalSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh/Google.Solutions.IapDesktop.Extensions.Ssh.csproj
sources/Google.Solutions.IapDesktop.Extensions.Ssh/Services/SshExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh/Views/Terminal/SshTerminalPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh/Views/Terminal/SshTerminalPaneViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Ssh/Views/Terminal/SshTerminalSessionBroker.cs
sources/Google.Solutions.IapDesktop/Program.cs

Rename classes to disambiguate connections from sessions

Rename *ConnectionBroker to *SessionBroker

---

sources/README.md

Add instructions to create a Client ID.

---

sources/Google.Solutions.IapDesktop.Application/Resources/About.rtf

* Include full copyright notices
* Add libssh2, vtnetcore, openssl

Extend About text

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminal.cs

Draw caret at proper position when caret is at start of
line, meaning there is no preceeding text to use as
reference.
This fixes an issue where the caret jumps to (0, 0) when
editing files in vim or other editors.

Fix caret drawing when positioned at start of line

---

sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/EventLog/EventLogViewModel.cs

This fixes an issue where the links in the EventViewer
threw an UnknownServiceException.

Lookup CloudConsoleService by interface

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

* Update dependencies to latest version
* Ensure that the vtnetcore version with the bracketed text mode-fix is used
cf. #483

Update dependencies to .13

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

* Use the vtnetcore version that contains the CR/LF patch
* Add test that verifies proper handling of CR/LF

b/188026963 Update dependencies to use latest vtnetcore version

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestSshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ShellExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Ssh/SshConnectionService.cs

b/188153403 Add 'Connect new session' command to start new SSH session 

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

Update to latest vtnetcore package that contains the fix
for single-parameter OSC sequence handling.

b/189199398 Update dependencies

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminalKeyHandler.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminalKeyTranslation.cs

Use xterm-compatible translations for numpad keys
This is to address #512

Fix key translation for numpad keys

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/TestMainForm.cs
sources/Google.Solutions.IapDesktop.Application/Views/DocumentWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/IMainForm.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Minimize and restore both windows
* Fix related issue where the desktop size is restored
to the client area restoring when it should respect
the connection setting (AutoAdjust/ClientArea/..)
This addresses #500.

b/191854202 Allow minimizing window from within full-screen mode

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestWindowsCredentialAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/WindowsCredentialAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Credentials/TestCredentialsService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPaneWithGroupPolicies.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/CredentialsService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/GenerateCredentialsDialog.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/GenerateCredentialsDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/GenerateCredentialsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/ShowCredentialsDialog.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/ShowCredentialsDialog.cs
sources/Google.Solutions.IapDesktop/Program.cs

* Expose `AddToAdministartors` flag in API, but not in UI as it does
not permit RDP logins
* Update design of dialogs
* Extract view model

b/193201006 Refactor credential dialogs

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/SecureConnect/TestSecureConnectEnrollment.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Settings/TestApplicationSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestGeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestNetworkOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestScreenOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/WindowTestFixtureBase.cs
sources/Google.Solutions.IapDesktop.Application/Services/Settings/ApplicationSettingsRepository.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/installer/policies/IapDesktop.admx

* Evaluate policies from HKCU
* Prefer HKLM-based policies in case of a conflict
* Extend ADMX policy definitions

b/193864987 Evaluate user-based policies

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Credentials/TestGenerateCredentialsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/GenerateCredentialsDialog.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/GenerateCredentialsDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/GenerateCredentialsViewModel.cs

Extend credential dialog to verify that the
username is not reserved

Check for reserved Windows usernames

---

sources/Google.Solutions.IapTunneling/Iap/Messages.cs
sources/Google.Solutions.IapTunneling/Iap/SshRelayStream.cs

Map VM lookup failures like access failures and
theow an UnauthorizedException.

b/198398480 Handle VM lookup failures

---

sources/Google.Solutions.Common.Test/Auth/TestGoogleAuthAdapter.cs
sources/Google.Solutions.Common.Test/Integration/InstanceFactory.cs
sources/Google.Solutions.IapDesktop.Application.Test/ObjectModel/TestModelCachingViewModelBase.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestComputeEngineAdapter.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestInstanceExtensions.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Integration/TestJobService.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Settings/TestAuthSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectPicker/TestProjectPickerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugJobServiceWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/Adapters/TestAuditLogStorageSinkAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/Adapters/TestStorageAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/UsageReport/TestReportBuilderLicenseAnnotations.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/UsageReport/TestReportBuilderSources.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Views/EventLog/TestEventLogViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Views/SerialOutput/TestAnsiTextReader.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Views/SerialOutput/TestAnsiTokenReader.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Views/SerialOutput/TestSerialOutputModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Rdp/TestRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestAuthorizedKeyService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestOsLoginService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestSshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Tunnel/TestTunnelBrokerService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Tunnel/TestTunnelService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Tunnel/TestTunnelServiceWithMtls.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/ConnectionSettings/TestConnectionSettingsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Credentials/TestCredentialPrompt.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPaneWithGroupPolicies.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/TunnelsViewer/TestTunnelsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/TunnelsViewer/TunnelsViewModel.cs

Add missing ConfigureAwait calls

Fix code analysis nits

---

sources/Google.Solutions.Common.Test/Diagnostics/TestTraceSourceExtensions.cs
sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.Common/Diagnostics/TraceSourceExtensions.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config

Include vtnetcore logs in application log to simplify diagnostics

b/210799432 Forward vtnetcore logs to common TraceSource

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config

- Show error message when parsing xterm data failed
- Update to latest (patched) vtnetcore version
This addresses #576

b/210967081 Improve handling of xterm parsing errors

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

Update dependencies to use latest version

b/208718649 Update to libssh2 1.10

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/packages.config
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Activity/Google.Solutions.IapDesktop.Extensions.Activity.csproj
sources/Google.Solutions.IapDesktop.Extensions.Activity/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Os/Google.Solutions.IapDesktop.Extensions.Os.csproj
sources/Google.Solutions.IapDesktop.Extensions.Os/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/app.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.IapDesktop/packages.config
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj

The latest package (3.1.0) is unsigned

Downgrade DockPanelSuite back to 3.0.6

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/ConnectionSettings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPaneWithGroupPolicies.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ConnectionSettings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs

Add connection options for sharing:
- Devices
- Drives
- Local ports
- Printers
- Smart cards
Sharing is disabled by default. This addresses #572.

b/210387695 Enable RDP device redirection

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/Authorization/TestAuthorization.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Authorization/TestSignInAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/SignInAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Authorization/AppAuthorization.cs

Pass login hint to speed up browser flow for reauthorization

b/213846549 Set login hint for reauthorize

---

sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.IapDesktop/Windows/AuthorizeDialog.cs
sources/Google.Solutions.IapDesktop/Windows/AuthorizeViewModel.cs

b/214344362 Refactor AuthorizeDialog

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPaneWithGroupPolicies.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ConnectionSettings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs

Add setting to disable NLA, required when connecting
to VMs that use a custom credential service provider.
This addresses #604.

b/216249096 Add RDP connection setting for NLA

---

sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

Use TimeSpan.TotalDays instead of TimeSpan.Days

b/218301842 Fix update check calculation

---

sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Events/Access/TestOsLoginCheckPolicyEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Events/Access/TestOsLoginContinueSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Events/Access/TestOsLoginStartSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/Adapters/TestAuditLogAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Access/OsLoginCheckPolicyEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Access/OsLoginContinueSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Access/OsLoginEventBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Access/OsLoginStartSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Google.Solutions.IapDesktop.Extensions.Activity.csproj
sources/Google.Solutions.IapDesktop.Extensions.Activity/Logs/LogRecord.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Services/Adapters/AuditLogAdapter.cs

* Use instance_id label introduced in b/186845475
* Extend log filter to use new label
* Extend OS Login events to include instance id

b/214888940 Show OS Login events by instance

---

sources/Google.Solutions.Common.Test/Diagnostics/TestBugReport.cs
sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.Common/Diagnostics/BugReport.cs
sources/Google.Solutions.Common/Google.Solutions.Common.csproj
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/BuganizerAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/GithubAdapter.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/ErrorDialog.Designer.cs
sources/Google.Solutions.IapDesktop/Windows/ErrorDialog.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Show `ErrorDialog` when encountering unhandled WinForms exceptions
* Add button to report an unhandled exception
* Use common format for bug reports

b/222635358 Show error dialog for unhandled exceptions

---

sources/Google.Solutions.Ssh/Auth/SshKeyPair.cs

In rare cases, creating a key can fail with error code
NTE_EXISTS, despite the previous check for key existance.
This addresses #631.

Improve error message when creating crypto key fails

---

sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/Native/TestSshFileCopyChannel.cs
sources/Google.Solutions.Ssh.Test/SshFixtureBase.cs
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/Native/FilePermissions.cs
sources/Google.Solutions.Ssh/Native/SshAuthenticatedSession.cs
sources/Google.Solutions.Ssh/Native/SshFileCopyChannel.cs
sources/Google.Solutions.Ssh/SshWorkerThread.cs

* Extend SshAuthenticatedSession
* Add upload/download channel
This is a building block for #633

b/227935260 Extend SSH library to enable SCP operations

---

sources/Google.Solutions.IapDesktop.Application/Util/SingletonApplicationBase.cs

When the first instance is run at a higher IL than the second
instance, accessing the Mutex (and named pipe) fails for the
second instance. Maintaining separate Mutextes and named pipes,
one per IL, would work, but seems unnecessaily complex.
Ignore existing instance when its Mutex is unaccessible, and
allow a second/third/... instance to be launched.
Addresses #645.

b/228706736 Ignore existing instance when running at different IL

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/WindowTestFixtureBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopPaneWithGroupPolicies.cs

* Simplify code
* Ensure SynchronizationContext-awareness

b/227935260 Replace AwaitEvent by AssertRaisesEventAsync 

---

sources/Google.Solutions.IapDesktop.Application/Views/Dialog/ConfirmationDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshKeys/TestAuthorizedPublicKeysViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshTerminalPaneViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/TunnelsViewer/TestTunnelsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/TunnelsViewer/TunnelsViewModel.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

When using a custom profile, allow users to delete
the current profile when signing out.

b/230591185 Allow profile deletion on sign-out

---

sources/Google.Solutions.IapDesktop.Application/Services/Integration/JobService.cs

Cancel reauth process when user clicks "Cancel"
in job dialog, clean up resources and stop
listener.

b/235703345 Allow cancellation of reauth

---

dependencies/makefile
dependencies/vcpkg-ports/libssh2/0001-Fix-UWP.patch
dependencies/vcpkg-ports/libssh2/0002-fix-macros.patch
dependencies/vcpkg-ports/libssh2/CONTROL
dependencies/vcpkg-ports/libssh2/portfile.cmake
dependencies/vcpkg-ports/libssh2/vcpkg.json

* Build libssh 1.10 with OpenSSL 1.1.1m
* Update to newer vcpkg format

b/234686081 Update libssh2 port config

---

sources/Google.Solutions.Common/Google.Solutions.Common.csproj
sources/Google.Solutions.Common/Interop/ComReference.cs
sources/Google.Solutions.IapDesktop.Application.Test/Controls/TestBadgeIcon.cs
sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application/Controls/BadgeIcon.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.IapDesktop/Interop/TaskBarList.cs
sources/Google.Solutions.IapDesktop/Windows/MainFormViewModel.cs

When using a non-standard profile, show a taskbar overlay
that indicates the name of the profile.

b/236070502 Indicate active profile in taskbar overlay

---

sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Services/ThemeService.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugThemeWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugThemeWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugThemeWindow.resx
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.resx
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/EventLog/EventLogWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/EventLog/EventLogWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/EventLog/EventLogWindow.resx
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/SerialOutput/SerialOutputWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/SerialOutput/SerialOutputWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/SerialOutput/SerialOutputWindow.resx
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysWindow.resx
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/TunnelsViewer/TunnelsWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/TunnelsViewer/TunnelsWindow.designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/TunnelsViewer/TunnelsWindow.resx
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.Designer.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.resx
sources/Google.Solutions.IapDesktop/Windows/MainFormViewModel.cs

* Add ThemeService to have one place for loading and
applying themes
* Add debug window for inspecting color palette

b/239991254 Refactor theming

---

sources/Google.Solutions.IapDesktop.Application.Test/Controls/TestBindableListView.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectPicker/TestProjectPickerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Controls/BindableListView.cs
sources/Google.Solutions.IapDesktop.Application/Controls/SearchableList.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Controls/SearchableList.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectPicker/ProjectPickerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectPicker/ProjectPickerWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectPicker/ProjectPickerWindow.cs

* Extend ProjectPicker to allow multi-select 
* Exctend SearchableListView to support Ctrl+A shortcut
* Reload view model once after adding multiple projects

b/241998375 Add multiple projects at once

---

sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/ToolWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ShellExtension.cs
sources/Google.Solutions.Mvvm.Test/Commands/TestCommand.cs
sources/Google.Solutions.Mvvm.Test/Commands/TestCommandContainer.cs
sources/Google.Solutions.Mvvm.Test/Google.Solutions.Mvvm.Test.csproj
sources/Google.Solutions.Mvvm/Commands/Command.cs
sources/Google.Solutions.Mvvm/Commands/CommandContainer.cs

* Allow command handlers to be async
* Handle exceptions in command container, including
exceptions thrown asynchronously
* Remove async void methods in extensions

b/238571887 Async command handlers

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestComputeEngineAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/ComputeEngineAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/IComputeEngineAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Windows/WindowsCredentialService.cs

- Rephrase error messages
- Add exception handler for metadata methods
- Remove obsolete methods

b/242649759 Cleanup error handling in GCE adapter

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ShellExtension.cs

Swap positions of "Refresh" and "Connection settings"

b/243467448 Reorder context menu items

---

sources/Google.Solutions.IapDesktop.Extensions.Management/Services/ActiveDirectory/DomainJoinService.StartupScript.ps1

- Use shutdown.exe instead of Restart-Computer cmdlet
- Specify reason 'Operating System: Reconfiguration (Planned)'

b/243849940 Specify reason for restart after domain join

---

sources/Google.Solutions.IapDesktop/Program.cs

This is to fix the 'Tools > Options' command throwing
an UnknownServiceException.
Cf. #773

b/244787398 Move ExceptionDialog to base layer

---

sources/Google.Solutions.IapDesktop.Application/Views/ToolWindow.cs

Save and restore dock state, regardless of whether the window 
was closed manually or closed during shutdown.
Previously, the restore logic only applied during startup.

b/243087061 Restore tool window dock state after closing window

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectExplorer/TestProjectExplorerSettings.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Services/Settings/ApplicationSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerSettings.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs

b/245652300 Auto expand/collapse projects on startup

---

sources/Google.Solutions.IapTunneling/Iap/SshRelaySession.cs
sources/Google.Solutions.IapTunneling/Iap/SshRelayStream.cs

Change trace messages to only include the
truncated session ID.

b/249442428 Truncate SID in logs

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Settings/TerminalSettings.cs

Use a slightly lighter xterm standard color as default

b/251247986 Use 236 as default background color

---

sources/Google.Solutions.IapDesktop.Application/Services/Adapters/BuganizerAdapter.cs

Change format, add note about answering questions
to help fix the issue.

b/251246347 Extend bug template

---

sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

Update libssh2, vtnetcore dependencies to pull in OpenSSL 1.1.1p

b/249915031 Update libssh2, vtnetcore dependencies

---

dependencies/makefile
dependencies/sources/dockpanelsuite/makefile

- Ensure backward compatibility
- Use classic project to ensure Kokoro compatibility

b/252922267 Use 3.0.6 instead of 3.1

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/packages.config
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.IapDesktop/packages.config
sources/Google.Solutions.Testing.Application/Google.Solutions.Testing.Application.csproj
sources/Google.Solutions.Testing.Application/packages.config

- Use version 3.6.02 from local package source
- Remove Themes package reference as the local
package includes the Theme DLL

b/252922267 Update DockPanelSuite

---

sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config

Update to latest version to pull in fixes for terminal color handling

b/251538443 Update vtnetcore

---

sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config

Update to the latest version that includes the patch for fixing DECRC command handling

b/253777494 Update vtnetcore

---

dependencies/sources/libssh2/makefile
dependencies/sources/libssh2/vcpkg-ports/openssl/portfile.cmake
dependencies/sources/libssh2/vcpkg-ports/openssl/vcpkg.json

b/256280974 Update libssh2 dependencies

---

sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

Update package to pull in OpenSSL 1.1.1s

b/256280974 Update libssh2

---

sources/Google.Solutions.Mvvm/Controls/FileBrowser.cs
sources/Google.Solutions.Mvvm/Shell/FileTypeCache.cs

* Avoid touchinh the image list during dispose, because the file icons might be disposed already
* Interlock file type cache modifications

b/257177354 Fix dispose race condition

---

sources/Google.Solutions.IapDesktop.Application/Services/Adapters/Browser.cs
sources/Google.Solutions.IapDesktop/Windows/AuthorizeDialog.Designer.cs
sources/Google.Solutions.IapDesktop/Windows/AuthorizeDialog.cs

Add "Sign in with Chrome (Guest mode)" to Authorize screen to start Chrome with --guest flag.

b/258042651 Add option to sign in with Guest mode

---

sources/Google.Solutions.IapDesktop/Program.cs

* Set event later in the lifecycle to ensure that the window is fully initialized and shown before acceping invokes from the named pipe thread
* Stop handling invokes when the window is in the process of being closed

b/261727410 Avoid invocation when window not ready yet/anymore

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ConnectionSettings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RdpExceptions.cs

* Expose connection timeout in settings window
* Add remark to error message suggesting that the timeout can be increased

b/260737840 Expose RDP connection timeout in settings

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Host/TestInstall.cs
sources/Google.Solutions.IapDesktop.Application.Test/Host/TestProfile.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/TestUpdateService.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Host/Install.cs
sources/Google.Solutions.IapDesktop.Application/Host/Profile.cs
sources/Google.Solutions.IapDesktop.Application/Services/UpdateService.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs
sources/Google.Solutions.IapDesktop/Windows/MainFormViewModel.cs

* Add Install class
* Maintain history of previously installed versions

b/264808477 Add class to represent current installation

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestAppearanceOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestOptionsViewModelBase.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Theme/ThemeSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/AppearanceOptionsSheet.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/AppearanceOptionsSheet.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/AppearanceOptionsSheet.resx
sources/Google.Solutions.IapDesktop.Application/Views/Options/AppearanceOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/GeneralOptionsSheet.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/NetworkOptionsSheet.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/OptionsDialog.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/OptionsViewModelBase.cs
sources/Google.Solutions.IapDesktop.Application/Views/Properties/PropertiesDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Options/SshOptionsSheet.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Options/TerminalOptionsSheet.Designer.cs
sources/Google.Solutions.Mvvm.Test/Binding/TestObservableProperty.cs
sources/Google.Solutions.Mvvm.Test/Controls/TestBindableComboBox.cs
sources/Google.Solutions.Mvvm.Test/Google.Solutions.Mvvm.Test.csproj
sources/Google.Solutions.Mvvm/Binding/ObservableProperty.cs
sources/Google.Solutions.Mvvm/Controls/BindableComboBox.cs
sources/Google.Solutions.Mvvm/Controls/BindableListView.cs
sources/Google.Solutions.Mvvm/Controls/ControlExtensions.cs
sources/Google.Solutions.Mvvm/Google.Solutions.Mvvm.csproj

* Add 'Appearance' options sheet to select theme
* Add BindableComboBox for enum <-> combobox
binding

b/265601653 Appearance options

---

dependencies/makefile
dependencies/sources/dockpanelsuite/makefile
dependencies/sources/libssh2/makefile
dependencies/sources/libssh2/vcpkg-ports/openssl/portfile.cmake
dependencies/sources/libssh2/vcpkg-ports/openssl/vcpkg.json
dependencies/sources/vtnetcore/makefile

* Use latest vcpkg tag
* Update openssl portfile to download, use 1.1.1t
* Increment tag

b/267706676 Update OpenSSL to 1.1.1t

---

sources/Google.Solutions.IapDesktop.Application/Views/ProjectPicker/ProjectPickerView.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/EventLog/EventLogView.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/PackageInventory/PackageInventoryViewBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysView.cs
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj

Add commands before binding so that they can be
themed automatically

b/265601653 Apply theme to copy commands

---

sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

This pulls in OpenSSL 1.1.1t as transitive dependency

b/267706676 Update libssh2 to 1.10.0.31

---

sources/Google.Solutions.IapDesktop.Application/Views/Options/AppearanceOptionsSheet.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/AppearanceOptionsViewModel.cs

* Fix alignment
* Add line break in not supported-warning

b/271349058 Fix layout of Appeance tab

---

sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Views/EventLog/TestEventLogViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/EventLog/EventLogView.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/EventLog/EventLogViewModel.cs

* Add missing binding
* Clear selection and disable button when model changed

b/271370075 Control status of 'Open Logs' button

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopView.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopViewModel.cs

Track and display state of RDP control (Debug only)

b/271514217 Track RDP connection state

---

sources/Google.Solutions.Mvvm.Test/Binding/TestObservableFunc.cs
sources/Google.Solutions.Mvvm.Test/Binding/TestObservableProperty.cs
sources/Google.Solutions.Mvvm.Test/Binding/TestThreadSafeObservableProperty.cs
sources/Google.Solutions.Mvvm.Test/Google.Solutions.Mvvm.Test.csproj
sources/Google.Solutions.Mvvm/Binding/ObservableFunc.cs
sources/Google.Solutions.Mvvm/Binding/ObservableProperty.Builder.cs
sources/Google.Solutions.Mvvm/Binding/ObservableProperty.cs
sources/Google.Solutions.Mvvm/Google.Solutions.Mvvm.csproj

* Add ThreadSafeObservableProperty
* Split classes, tests into separate files

Add ThreadSafeObservableProperty

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/Properties/TestPropertiesInspectorWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/Properties/IPropertiesInspectorViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/Properties/PropertiesInspectorViewBase.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Properties/PropertiesInspectorViewBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Views/InstanceProperties/TestInstancePropertiesInspectorViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Views/PackageInventory/TestPackageInventoryViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/InstanceProperties/InstancePropertiesInspectorViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/PackageInventory/PackageInventoryViewBase.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/PackageInventory/PackageInventoryViewBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/PackageInventory/PackageInventoryViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/ConnectionSettings/TestConnectionSettingsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshKeys/TestAuthorizedPublicKeysViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/ConnectionSettings/ConnectionSettingsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysView.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshKeys/AuthorizedPublicKeysViewModel.cs

* Replace SplitContainer with NotificationBarPanel 
* Refactor view models to use observable properties

b/271356233 Use NotificationBarPanel in all tool windows

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/Integration/TestSessionBroker.cs
sources/Google.Solutions.IapDesktop.Application/Services/Integration/SessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestSshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshTerminalSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Rdp/RdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Ssh/SshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalSessionBroker.cs

Fix URL-based session activation when main window is currently minimized.
When the main window is minimized, activating a session does not immediately cause the session to be active.

b/273139588 Fix session activation

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/Authorization/TestAuthorizeViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/Authorization/AuthorizeView.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Authorization/AuthorizeView.cs
sources/Google.Solutions.IapDesktop.Application/Views/Authorization/AuthorizeViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopView.cs

* Show window in taskbar
* Extend title to include friendly name

b/273386816 Show Authorize window in taskbar

---

sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Views/IMainWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/UrlCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/EventLog/EventLogCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/TestConnectionCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ShellExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/ConnectionCommands.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs
sources/Google.Solutions.Testing.Application/Views/TestMainForm.cs

* Use a command in place of the existing IUrlHandler interface
* Improve error handling

b/274025818 Use command to dispatch iap-rdp:/// URLs

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Diagnostics/DiagnosticsCommands.cs

* Add forms to customize parameters
* Show running/stopped status

b/274025818 Extend diagnostics page

---

sources/Google.Solutions.IapDesktop.Application/Views/Authorization/AuthorizeView.Designer.cs

Increase size to prevent a line wrap for long
version numbers

b/273140012 Fix size of version label

---

sources/Google.Solutions.IapDesktop.Application/Views/Options/OptionsDialog.cs
sources/Google.Solutions.Mvvm/Binding/PropertiesView.cs
sources/Google.Solutions.Mvvm/Binding/PropertiesViewModel.cs

Display "Options" instead of the default dialog
title.

b/275629092 Fix window title of Options dialog

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Data/TestIapRdpUrlExtensions.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Connection/TestRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopViewWithGroupPolicies.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestConnectCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestConnectInstanceComand.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestConnectRdpUrlCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestInstanceSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Data/RdpSessionParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Connection/RdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/SessionBroker.cs

* Track source of parameters
* Apply accent color in session broker

b/275621335 Use tab accent color for URL-initiated sessions

---

sources/Google.Solutions.Apis/Compute/InstanceExtensions.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestInstanceExtensions.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/HelpAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/InstanceProperties/InstancePropertiesInspectorModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Session/TestRdpSessionContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Session/TestRdpSessionParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Session/TestSessionContextFactoryForRdp.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Session/TestSessionContextFactoryForSsh.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Session/TestSshSessionContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Session/TestSshSessionParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Session/TestTransport.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Settings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshTerminalView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Session/RdpSessionContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Session/RdpSessionParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Session/SessionContextBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Session/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Session/SshSessionContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Session/SshSessionParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Session/Transport.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/SessionBroker.cs

* Add transport for connecting to a VM's primary internal IP directly
* Expose SSH and RDP connection setting in UI
ref #870

b/275473315 Connect via VPN/Interconnect

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/TestMenuCommandAttribute.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/ObjectModel/IServiceCategoryProvider.cs
sources/Google.Solutions.IapDesktop.Application/ObjectModel/ServiceRegistry.cs
sources/Google.Solutions.IapDesktop.Application/Views/MenuCommandAttribute.cs
sources/Google.Solutions.IapDesktop.Application/Views/MenuCommandBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Views/InstanceControlCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Diagnostics/DiagnosticsCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/ConnectCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/ConnectInstanceCommandBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/SessionCommands.cs

* Support nested menus
* Specify the menu to extend in attribute

b/279510055 Menu-specific commands

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/SessionBroker.cs

Show user and instance information in session tooltip.
In debug builds, include all parameters.

b/275015416 Show session information in tooltip

---

sources/Google.Solutions.IapDesktop.Application/Host/SingletonApplicationBase.cs

* Make sure that the pipe is disconnected before
attempting to create a new pipe with the same name.
* Back off and retry if a dangling pipe prevents the
creation of a new pipe.

b/280666330 Explicitly disconnect pipe

---

sources/Google.Solutions.Iap.Test/Protocol/TestEchoOverIapIndirectTunnel.cs
sources/Google.Solutions.Iap.Test/Protocol/TestHttpOverIapIndirectTunnel.cs
sources/Google.Solutions.Iap.Test/TestIapListener.cs
sources/Google.Solutions.Iap/IapListener.cs
sources/Google.Solutions.Iap/Net/PortFinder.cs
sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Transport/TestIapTransportFactory.cs
sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Transport/TestIapTunnel.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/IapTunnel.cs
sources/Google.Solutions.IapDesktop.Core/Properties/AssemblyInfo.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/IapTransport.cs

* Use IPEndPoint instead of port number
* Remove factory methods

b/271897783 Simplify IapListener API

---

sources/Google.Solutions.IapDesktop.Application/ToolWindows/Properties/PropertiesInspectorViewBase.Designer.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/Properties/PropertiesInspectorViewBase.resx
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs

Use a more intuitive order for properties in connection window

b/287539150 Optimize order of connection settings

---

sources/Google.Solutions.Iap.Test/Net/TestPortFinder.cs
sources/Google.Solutions.Iap/Net/PortFinder.cs

Reuse the same RNG instance for port allocations

b/286598349 Reuse RNG for port-allocation

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/App/TestSsms.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/App/TestSsmsClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/IWindowsAppClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/Ssms.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/SsmsClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/OpenWithAppCommand.cs

* Load icon from EXE file
* Extend menu command to use icon if available

b/287533965 Show SSMS icon in context menu

---

sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Menu.cs
sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolContext.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/App/TestAppContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/App/TestSsmsClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/App/TestOpenWithAppCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/AppContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/IWindowsAppClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/IWindowsProtocolClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/SsmsClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/ProjectExplorerNodeExtensions.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpCredential.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/SshCredential.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/AppCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/OpenWithClientCommand.cs
sources/Google.Solutions.Mvvm/Binding/ViewModelBase.cs
sources/Google.Solutions.Platform/Dispatch/Win32ChildProcessFactory.cs

Use a setting to determine whether to use Windows auth/NLA or SQL Server
auth, and remove the extra menu commands

b/286161182 Add setting to determine authentication method

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestCredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Theme/ThemeService.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/UsernameDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Debug/Dialog/DialogCommands.cs
sources/Google.Solutions.Mvvm/Controls/RichTextBoxExtensions.cs
sources/Google.Solutions.Mvvm/Controls/TextBoxExtensions.cs
sources/Google.Solutions.Mvvm/Theme/WindowsSystemDialogRuleset.cs

Add a CredUI-style dialog that prompts for a username

b/286161182 Username dialog

---

sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolFactory.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolFactory.cs

Add version attribute and verify it when parsing config files.

b/289119099 Include version in protocol config files

---

sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolClient.cs
sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolFactoryConfigurationSection.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolClient.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/Config/Protocols/mysql.iap

Use {x} instead of $x$ for placeholders in configuration files

b/289861037 Change placeholder syntax

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Session/TestConnectCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/ConnectCommands.cs

This lets users create multiple connections to the same server with different credentials

b/283176574 Start new RDP session when connecting "as user"

---

sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceProperties/InstancePropertiesInspectorModel.cs

* Incldue service account and shielded VMs settings
* Clean up model class initialization

b/269352024 Show security settings in Instance Properties window

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/Config/chrome-8080.iapc

Incrporate port number in user data dir path so that
each tunnel is assigned a sepatate Chrome process.

b/290287341 Force separate Chrome instance per tunnel 

---

sources/Google.Solutions.Apis.Test/Logging/TestLoggingAdapter.cs
sources/Google.Solutions.Apis/Client/RequestExtensions.cs
sources/Google.Solutions.Apis/Google.Solutions.Apis.csproj
sources/Google.Solutions.Apis/Logging/LoggingAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/TestAuditLogClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/ToolWindows/EventLog/TestEventLogViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Adapters/AuditLogAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/AuditLogClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/EventLog/EventLogViewModel.cs
sources/Google.Solutions.IapDesktop/Program.cs

* Exract LoggingAdapter and move to Apis project
* Remove reference to Cloud Logging client library

b/291845010 Refactor AuditLogAdapter

---

doc/site/sources/mkdocs.yml

Set site URL to ensure that sitemap.xml is generated correctly

b/293373828 Generate sitemap.xml

---

sources/Google.Solutions.IapDesktop.Application/Host/Adapters/HelpAdapter.cs
sources/Google.Solutions.IapDesktop.Core/HelpTopics.cs

Update help links to point to documentation site instead of Wiki.

b/293396857 Update links to documentation site

---

sources/Google.Solutions.Apis.Test/Client/TestPscAndMtlsAwareHttpClientFactory.cs
sources/Google.Solutions.Apis/Client/ClientServiceMtlsExtensions.cs
sources/Google.Solutions.Apis/Client/HttpClientHandlerExtensions.cs
sources/Google.Solutions.Apis/Client/PscAndMtlsAwareHttpClientFactory.cs
sources/Google.Solutions.Apis/Client/ServiceEndpointDirections.cs

b/291845010 Bypass proxy when connecting thru PSC

---

sources/Google.Solutions.Iap/IapInstanceTarget.cs
sources/Google.Solutions.IapDesktop.Application/Profile/Settings/AccessSettingsRepository.cs
sources/installer/policies/IapDesktop.admx

* Bypass proxy for IAP when PSC enabled
* Fix registry key in ADMX

b/291845010 Bypass proxy for IAP, fix ADMX key

---

sources/Google.Solutions.Apis/Client/ServiceRoute.cs

* Use configured handler
* Don't use host overrides as they're not required for probing

b/291845010 Fix PSC endpoint probing

---

doc/site/sources/docs/control-access-to-vms.md
sources/Google.Solutions.Apis.Test/Locator/TestAccessLevelLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestDiskTypeLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestImageLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestInstanceLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestLicenseLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestMachineTypeLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestNodeTypeLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestProjectLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestZoneLocator.cs
sources/Google.Solutions.Apis/Compute/InstanceExtensions.cs
sources/Google.Solutions.Apis/Google.Solutions.Apis.csproj
sources/Google.Solutions.Apis/Locator/AccessLevelLocator.cs
sources/Google.Solutions.Apis/Locator/GlobalResourceLocator.cs
sources/Google.Solutions.Apis/Locator/GlobalResourceLocator.tt
sources/Google.Solutions.Apis/Locator/ProjectLocator.cs
sources/Google.Solutions.Apis/Locator/ZonalResourceLocator.cs
sources/Google.Solutions.Apis/Locator/ZonalResourceLocator.tt
sources/Google.Solutions.Apis/Locator/ZoneLocator.cs
sources/Google.Solutions.IapDesktop.Core/ProjectModel/ProjectWorkspace.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Events/EventBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceProperties/InstancePropertiesInspectorModel.cs

Rename FromString to Parse to comply with .NET naming conventions

b/295426903 Rename FromString to Parse

---

sources/Google.Solutions.IapDesktop.Extensions.Management.Test/ToolWindows/InstanceProperties/TestInstancePropertiesInspectorModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceProperties/InstancePropertiesInspectorModel.cs

Fix NullReferenceException caused by a partially initialized structure

b/295742619 Handle partially populated guest OS info

---

sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestAuthorizeUserTunnelEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestOsLoginCheckPolicyEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestOsLoginContinueSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestOsLoginStartSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestSetCommonInstanceMetadataEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestSetMetadataEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Events/EventBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Logs/AuditLogRecord.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/EventLog/EventLogView.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/EventLog/EventLogView.cs

* Extract 'principalSubject' from logs
* Rename column to 'Principal'

b/297436033 Show 3PI principal in Event Logs window

---

sources/Google.Solutions.Apis/Auth/IAuthorization.cs
sources/Google.Solutions.IapDesktop.Application.Test/Profile/Auth/TestAuthorization.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/Auth/TestAuthorizeViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/TestJobService.cs
sources/Google.Solutions.IapDesktop.Application/Profile/Auth/Authorization.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeView.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeView.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/JobService.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Properties/launchSettings.json
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs
sources/Google.Solutions.Mvvm.Test/Binding/TestThreadSafeObservableProperty.cs
sources/Google.Solutions.Mvvm/Binding/ObservableProperty.cs
sources/Google.Solutions.Mvvm/Controls/ControlExtensions.cs
sources/Google.Solutions.Testing.Apis/Integration/TemporaryAuthorization.cs

Use same dialog for initial authorization and subsequently when a user's session expires

b/293969071 Use Authorize dialog for reauthorization

---

doc/site/sources/docs/connect-to-google-cloud.md
sources/Google.Solutions.IapDesktop.Application/Windows/Options/AccessOptionsSheet.Designer.cs

Use more concise language to save space

b/291845010 Fix wording on access options page

---

sources/Google.Solutions.Apis.Test/Analytics/TestMeasurementClient.cs
sources/Google.Solutions.Apis/Analytics/MeasurementClient.cs
sources/Google.Solutions.Apis/Analytics/MeasurementService.cs
sources/Google.Solutions.Apis/Analytics/MeasurementSession.cs
sources/Google.Solutions.Apis/ApiEventSource.cs
sources/Google.Solutions.Common/Util/LinqExtensions.cs
sources/Google.Solutions.IapDesktop.Application.Test/Host/Diagnostics/TestTelemetryListener.cs
sources/Google.Solutions.IapDesktop.Application.Test/Host/TestInstall.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/Options/TestGeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/ApplicationEventSource.cs
sources/Google.Solutions.IapDesktop.Application/Host/Adapters/HelpAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Host/Diagnostics/TelemetryCollector.cs
sources/Google.Solutions.IapDesktop.Application/Host/Diagnostics/TelemetryListener.cs
sources/Google.Solutions.IapDesktop.Application/Host/Install.cs
sources/Google.Solutions.IapDesktop.Application/Profile/Settings/ApplicationSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/GeneralOptionsSheet.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/GeneralOptionsSheet.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/GeneralOptionsSheet.resx
sources/Google.Solutions.IapDesktop.Application/Windows/Options/GeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/OptionsDialog.cs
sources/Google.Solutions.IapDesktop/OAuthClient.cs.default
sources/Google.Solutions.IapDesktop/Program.cs
sources/installer/policies/IapDesktop.adml
sources/installer/policies/IapDesktop.admx
sources/scripts/etw-trace.ps1

* Add optional setting to enable telemetry
* Expose setting in "General" options sheet and ADMX
* When enabled, relay selected ETW events to GA

b/298138274 ETW-based telemetry collection

---

sources/Google.Solutions.IapDesktop.Application.Test/Host/Diagnostics/TestBugReport.cs
sources/Google.Solutions.IapDesktop.Application/Host/Diagnostics/BugReport.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/ExceptionDialog.cs
sources/Google.Solutions.IapDesktop/Windows/ErrorDialog.cs

Add line indicating whether this report was triggered by a crash or a handled exception.

b/297066915 Indicate source in bug reports

---

sources/Google.Solutions.Apis.Test/Auth/Gaia/TestGaiaOidcSession.cs
sources/Google.Solutions.Apis.Test/Auth/Iam/TestWorkforcePoolSession.cs
sources/Google.Solutions.Apis/Auth/Gaia/GaiaOidcSession.cs
sources/Google.Solutions.Apis/Auth/IOidcSession.cs
sources/Google.Solutions.Apis/Auth/Iam/WorkforcePoolClient.cs
sources/Google.Solutions.Apis/Auth/Iam/WorkforcePoolSession.cs
sources/Google.Solutions.Apis/Auth/OidcSessionBase.cs
sources/Google.Solutions.IapDesktop.Application.Test/Host/Adapters/TestCloudConsole.cs
sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Host/Adapters/CloudConsole.cs
sources/Google.Solutions.IapDesktop.Application/Host/Adapters/CloudConsoleAdapter.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/ToolWindows/EventLog/TestEventLogViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/EventLog/EventLogViewModel.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Properties/launchSettings.json
sources/Google.Solutions.Platform/Net/Browser.cs
sources/Google.Solutions.Testing.Apis/Integration/TemporaryAuthorization.cs

Use session information to select between 
* Regular Cloud Console
* Secure Console
* BYOID Console

b/301857388 Vary Cloud Console URI based on session

---

sources/Google.Solutions.Apis.Test/Compute/TestOsLoginClient.cs
sources/Google.Solutions.Apis/Auth/Iam/NotSupportedForWorkloadIdentityException.cs
sources/Google.Solutions.Apis/Compute/OsLoginClient.cs
sources/Google.Solutions.Apis/HelpTopics.cs

Show more descriptive error when trying to use OS Login with workforce identity federation.

b/294784810 Show more descriptive error for WF/OS Login

---

sources/Google.Solutions.Common.Test/Util/TestExceptionExtensions.cs
sources/Google.Solutions.Common/Util/ExceptionExtensions.cs
sources/Google.Solutions.IapDesktop.Application/Host/Diagnostics/BugReport.cs

Include IL offset in stack trace because PDB information is typically not available on user systems.

b/304643218 Include IL offsets in bug report

---

sources/Google.Solutions.IapDesktop.props
sources/Google.Solutions.Ssh/Cryptography/ECDsaExtensions.cs
sources/makefile

Change build target from net462 to net47, unblocking access to ECDSA and High DPI support.

b/304843871 Target net47

---

doc/site/sources/docs/create-profiles.md

Add section "Use a different Google account" to fix #1160.

b/311533227 Document switching Google accounts for existing profile

---

sources/Google.Solutions.Apis.Test/Auth/Iam/TestWorkforcePoolSession.cs
sources/Google.Solutions.Apis.Test/Compute/TestOsLoginClient.cs
sources/Google.Solutions.Apis/Auth/Iam/IWorkforcePoolSession.cs
sources/Google.Solutions.Apis/Auth/Iam/WorkforcePoolSession.cs
sources/Google.Solutions.Apis/Client/ApiKey.cs
sources/Google.Solutions.Apis/Compute/OsLoginClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestKeyAuthorizer.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestKeyAuthorizerAndAuthenticate.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestOsLoginCertificateSigner.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestOsLoginProfile.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/KeyAuthorizer.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/MetadataAuthorizedPublicKey.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/OsLoginCertificateSigner.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/OsLoginProfile.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/SshAuthorizedKeyCredential.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/SshTerminalViewModel.cs
sources/Google.Solutions.IapDesktop/OAuthClient.cs.default
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.Ssh/Cryptography/EcdsaSigner.cs
sources/Google.Solutions.Ssh/Cryptography/RsaSigner.cs
sources/Google.Solutions.Testing.Apis/Auth/TemporaryPrincipal.cs
sources/Google.Solutions.Testing.Apis/Auth/TemporaryServiceAccount.cs
sources/Google.Solutions.Testing.Apis/Auth/TemporarySession.cs
sources/Google.Solutions.Testing.Apis/Auth/TemporaryWorkforcePoolSubject.cs
sources/Google.Solutions.Testing.Apis/Integration/CredentialAttribute.cs
sources/Google.Solutions.Testing.Apis/Integration/InstanceAttribute.cs
sources/Google.Solutions.Testing.Apis/Integration/PredefinedRole.cs
sources/Google.Solutions.Testing.Apis/Integration/TestProject.cs

When signed in with workforce identity federation, obtain and use an OS Login certificate instead of importing the SSH key.
#1158

b/308213280 OS Login with workforce identity federation

---

sources/Google.Solutions.Apis.Test/Compute/TestWindowsCredentialGenerator.cs
sources/Google.Solutions.Apis/Compute/WindowsCredentialGenerator.cs
sources/Google.Solutions.IapDesktop.Application/Host/Install.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/CngKeyName.cs
sources/Google.Solutions.Testing.Apis/Integration/CredentialAttribute.cs
sources/Google.Solutions.Testing.Apis/Integration/InstanceAttribute.cs

* Use SHA256.Create to ensure we use a FIPS-compliant
implementation
* Use OAEP with SHA256 for generating Windows credentials
if the VM's guest environment supports it

b/311436717 Use FIPS 140-2 compatible algorithms

---

sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestOsLoginCheckPolicyEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestOsLoginContinueSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Access/TestOsLoginStartSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Events/Access/OsLoginCheckPolicyEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Events/Access/OsLoginContinueSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Events/Access/OsLoginStartSessionEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Events/EventFactory.cs

Workforce identity-based logins use beta logs. Update filters to include these logs in the Event Log window.

b/310121254 Show OS Login beta logs

---

sources/Google.Solutions.IapDesktop.Application/Host/Adapters/HelpAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/InitializeManagementExtension.cs

Remove command as it's obsolete.

b/304845984 Remove "Analyze sole-tenant usage" command

---

sources/Google.Solutions.Ssh.Test/Native/TestSshConnectedSession.cs
sources/Google.Solutions.Ssh/Native/AuthenticationMetods.cs
sources/Google.Solutions.Ssh/Native/SshConnectedSession.cs
sources/Google.Solutions.Ssh/SshEventSource.cs

Refactor authentication logic and split authentication methods

b/251648787 Split logic for publickey, keyboard-interactive

---

sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/TaskDialog.cs

Don't show OK button as its redundant.

b/314034977 Remove OK button from Options/TaskDialog

---

sources/Google.Solutions.IapDesktop.Application.Test/Host/TestUpdateCheck.cs
sources/Google.Solutions.IapDesktop.Application/Host/UpdateCheck.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/TaskDialog.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Show version numbers in description
* Remove opt-out checkbox (users can still opt out via Tools > Options)

b/314034977 Change update dialog wording, buttons

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/SshTerminalView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/SshTerminalViewModel.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshConnectedSession.cs
sources/Google.Solutions.Ssh/Native/SshConnectedSession.cs

* Use server-provided name to set title
* Apply defaults for 2SV and keyboard-interactive use cases

b/314232878 Populate SSH prompt name dynamically

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Options/TestSshOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/SshOptionsSheet.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/SshOptionsViewModel.cs
sources/installer/policies/IapDesktop.adml
sources/installer/policies/IapDesktop.admx

* Extend ADMX
* Disable controls in Options dialog when policy applied

b/313968343 Add group policy for persistent/ephemeral SSH key

---

sources/Google.Solutions.Common/Util/Invariant.cs
sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/JobService.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/DebugJobServiceViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/ToolWindows/EventLog/TestEventLogViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/ToolWindows/InstanceProperties/TestInstancePropertiesInspectorViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/ToolWindows/PackageInventory/TestPackageInventoryViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/ToolWindows/SerialOutput/TestSerialOutputViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceControlCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/SshKeys/TestAuthorizedPublicKeysViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/SshKeys/AuthorizedPublicKeysViewModel.cs
sources/Google.Solutions.Testing.Application/Mocks/SynchronousJobService.cs
sources/Google.Solutions.Testing.Application/Views/TestMainForm.cs

* Extend interface, implementation to support Action callbacks
* Remove redundant mock implementations

b/295593849 Extend JobService to support Action callbacks

---

sources/Google.Solutions.IapDesktop.Application.Test/Client/TestGithubClient.cs
sources/Google.Solutions.IapDesktop.Application/Client/GithubClient.cs
sources/Google.Solutions.IapDesktop/OAuthClient.cs.default
sources/Google.Solutions.IapDesktop/Program.cs

Read GitHub repository name from configuration to simplify testing with fake repositories.

b/305593905 Read GitHub repository name from configuration

---

sources/Google.Solutions.Mvvm.Test/Controls/TestTaskDialog.cs
sources/Google.Solutions.Mvvm.Test/app.manifest
sources/Google.Solutions.Mvvm/Controls/TaskDialog.cs
sources/Google.Solutions.Mvvm/Controls/TaskDialogParameters.cs

Add new wrapper class for TaskDialogs that can be extended and mocked more easily.

b/315389635 Add TaskDialog

---

sources/Google.Solutions.IapDesktop.Core/ObjectModel/ServiceAttribute.cs

Seal class to improve lookup performance

b/315842988 Seal ServiceAttribute class

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/SshKeys/AuthorizedPublicKeysViewModel.cs

This fixes a NRE caused by a selection change while key deletion is ongoing.

b/316408604 Fix race condition when deleting SSH keys

---

sources/Google.Solutions.Apis/ApiEventSource.cs
sources/Google.Solutions.Apis/Client/PscAndMtlsAwareHttpClientFactory.cs
sources/Google.Solutions.Apis/Google.Solutions.Apis.csproj
sources/Google.Solutions.IapDesktop.Application.Test/TestNtlmProxy.cs

b/319015264 Add mitigation for race condition in BCL NTLM proxy authentication

---

sources/Google.Solutions.IapDesktop.Application/Windows/SessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Session/TestConnectCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Session/TestSessionCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/SessionCommands.cs

* Add _Close all_ and _Close others_ session commands
* Reorder commands

b/258736986 Add commands for closing multiple sessions

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestInputDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/InputDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/SystemInputDialog.cs

* Resize dialog height based on message size
* Optionally mask input

b/320201735 Resize input dialog automatically, allow masked input

---

sources/Google.Solutions.Apis.Test/Google.Solutions.Apis.Test.csproj
sources/Google.Solutions.Apis/Google.Solutions.Apis.csproj
sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.Iap.Test/Google.Solutions.Iap.Test.csproj
sources/Google.Solutions.Iap/Google.Solutions.Iap.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Core.Test/Google.Solutions.IapDesktop.Core.Test.csproj
sources/Google.Solutions.IapDesktop.Core/Google.Solutions.IapDesktop.Core.csproj
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/Google.Solutions.IapDesktop.Extensions.Diagnostics.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Google.Solutions.IapDesktop.Extensions.Management.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Google.Solutions.IapDesktop.Extensions.Session.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop.Tools.props
sources/Google.Solutions.IapDesktop.props
sources/Google.Solutions.IapDesktop.sln
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.Mvvm.Test/Google.Solutions.Mvvm.Test.csproj
sources/Google.Solutions.Mvvm/Google.Solutions.Mvvm.csproj
sources/Google.Solutions.Platform.Test/Google.Solutions.Platform.Test.csproj
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Testing.Apis/Google.Solutions.Testing.Apis.csproj
sources/Google.Solutions.Testing.Application/Google.Solutions.Testing.Application.csproj
sources/installer/Product.wxs

* Update managed dependencies (except NUnit, tools)
* Remove PlatformServices DLLs from MSI as per [1]
[1] https://github.com/googleapis/google-api-dotnet-client/issues/2561

b/321125909 Update NuGet dependencies

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestCredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs

Extend credential dialog to allow editing existing credentials

b/320201735 Edit existing credentials

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/SshTerminalView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/SshTerminalViewModel.cs
sources/Google.Solutions.Ssh.Test/Mocks.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshAuthenticatedSession.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshConnectedSession.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshSftpChannel.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshSftpFileChannel.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshShellChannel.cs
sources/Google.Solutions.Ssh.Test/SshFixtureBase.cs
sources/Google.Solutions.Ssh.Test/TestRemoteConnection.cs
sources/Google.Solutions.Ssh.Test/TestRemoteFileSystemChannel.cs
sources/Google.Solutions.Ssh.Test/TestRemoteShellChannel.cs
sources/Google.Solutions.Ssh/ISshCredential.cs
sources/Google.Solutions.Ssh/Native/HandleTable.cs
sources/Google.Solutions.Ssh/Native/NativeMethods.cs
sources/Google.Solutions.Ssh/Native/SshConnectedSession.cs
sources/Google.Solutions.Ssh/Native/SshSession.cs
sources/Google.Solutions.Ssh/SshWorkerThread.cs
sources/Google.Solutions.Ssh/StaticPasswordCredential.cs

Show password prompt when using authentication method `password` and the connection settings don't contain a password
Ref #1227

b/320201735 SSH: Prompt for password 

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Controls/RdpClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Controls/RdpExceptions.cs

Close session when user cancels a logon prompt

b/321623947 Handle aborted logon

---

sources/Google.Solutions.IapDesktop.Application/Windows/Menu.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ViewBindingContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/App/TestConnectAppProtocolWithClientCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/App/TestConnectAppProtocolWithoutClientCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/App/TestForwardLocalPortCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/AppProtocolContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/AppCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/ConnectAppProtocolWithClientCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/ConnectAppProtocolWithoutClientCommand.cs

* Load and expose commands for IAPC files that don't specify a client
* Show notification with local port number after connecting
Cf #1192

b/314873984 Support client-less IAPC files

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/DefaultAppProtocols/mysql-tunnel.iapc
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/DefaultAppProtocols/postgres-tunnel.iapc
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/DefaultAppProtocols/sqlserver-tunnel.iapc

Embed sample IAPC files for SQL Server, MySQL, Postgres

b/322096549 Add default tunnel configuration

---

sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/AppCommands.cs
sources/Google.Solutions.Mvvm.Test/Binding/Commands/TestContextCommandGroup.cs
sources/Google.Solutions.Mvvm/Binding/Commands/ContextCommandGroup.cs

* Add IContextCommandGroup to simplify adding sub-command
* Change session extension to use command groups

b/322097190 Introduce command groups

---

sources/Google.Solutions.Apis.Test/Auth/Iam/TestWorkforcePoolIdentity.cs
sources/Google.Solutions.Common.Test/Util/TestPrecondition.cs
sources/Google.Solutions.Common/Util/Precondition.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/SystemInputDialog.cs
sources/Google.Solutions.IapDesktop.props
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.Mvvm/Theme/WindowsRuleSet.cs
sources/Google.Solutions.Platform/UserEnvironment.cs
sources/Google.Solutions.Ssh/Native/SshSession.cs

* Remove legacy analyzers
* Enable new analysis for all projects
* Fix parameter check-warnings

Migrate code analyzers

---

sources/makefile

* Build and package both platforms
* Run integration tests for single platform only to save time

b/324318081 Build x86 and x64 in Kokoro

---

sources/Google.Solutions.IapDesktop.Application.Test/Client/TestGithubClient.cs
sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/Update/TestCheckForUpdateCommand.cs
sources/Google.Solutions.IapDesktop.Application/Client/GithubClient.cs
sources/Google.Solutions.IapDesktop.Application/Diagnostics/IReleaseFeed.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/Update/CheckForUpdateCommand.cs

When checking for updates, prefer downloads that match the current platform.

b/324468821 Use platform-specific download package

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestLinuxUser.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/LinuxUser.cs

Fixes https://github.com/GoogleCloudPlatform/iap-desktop/issues/1312

Relax the unix user validation constraint

---

doc/site/sources/docs/troubleshooting-signin.md

b/328541430 Document resolution for HSTS sign-in issues

---

sources/Google.Solutions.Settings.Test/Collection/TestGroupPolicyAwareRepository.cs
sources/Google.Solutions.Settings.Test/Google.Solutions.Settings.Test.csproj
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfBool.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfEnumFlags.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfInt.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfLong.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfString.cs
sources/Google.Solutions.Settings.Test/TestMergedSettingsStore.cs
sources/Google.Solutions.Settings/Collection/GroupPolicyAwareRepository.cs
sources/Google.Solutions.Settings/Google.Solutions.Settings.csproj
sources/Google.Solutions.Settings/MergedSettingsStore.cs

Refactor MergedSettingStore to support merging multiple stores

b/328680487 Allow merging multiple stores

---

sources/Build/Build.csproj

b/328669971 Update Wix toolset

---

sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerTrackingToolWindow.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.Designer.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/Update/ReleaseNotesView.cs
sources/Google.Solutions.IapDesktop.Application/Windows/DocumentWindow.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ToolWindowViewBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/AutoCloseView.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/DebugCommonControlsView.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/DebugDockingView.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/DebugJobServiceView.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/DebugServiceRegistryView.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/DebugThemeView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/SessionViewBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/SshTerminalView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/TerminalPaneBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Tunnels/TunnelsView.cs
sources/Google.Solutions.Mvvm.Test/Binding/Commands/TestDelegateCommand.cs
sources/Google.Solutions.Mvvm/Binding/Commands/DelegateCommand.cs

* Remove usage of InvokeActionAsync and use commands instead
* Add DelegateCommand to deal with drag/drop events
* Refactor base classes to not expect an IServiceProvier anymore

b/330639885 Simplify ToolWindow base classes

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Rdp/TestRdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Controls/RdpClient.ConnectionProperties.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.Settings/ComponentModel/SettingDescriptor.cs

* Add "Session type" connection parameter
* Connect to administrative session when session type set to "Admin"
Cf. #1326

b/330224089 Connect to admin session

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Controls/RdpExceptions.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs

* Propagare Admin flag to control
* Detect and react to failed redirects
Cf #1326

b/330224089 Fix admin session, RDSH redirect handling

---

sources/Google.Solutions.Apis.Test/Client/TestApiClientBase.cs
sources/Google.Solutions.Testing.Apis/Integration/TestProject.cs
sources/build.ps1

* Replace SecureConnect credentials with mock
* Add setting for service account impersonation

b/301518774 Allow running tests using service account impersonation

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Controls/RdpClient.cs
sources/Google.Solutions.Mvvm.Test/Input/TestKeyboardLayout.cs
sources/Google.Solutions.Mvvm/Input/KeyboardLayout.cs

While SendKeys worked correctlt on x64, it failed to properly deliver chords on x86.

b/333952175 Fix SendKeys on x86

---

doc/site/sources/docs/troubleshooting-rdp.md

* Add section on 'Type clipboard text' command

b/330783804 Documentation changes for version 2.41

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Options/TestOptionsViewModelBase.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/AccessOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/AppearanceOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/GeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/NetworkOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/OptionsViewModelBase.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/ScreenOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/SshOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/TerminalOptionsViewModel.cs

Perform all initialization in the constructor.

b/335348403 Refactor OptionsViewModelBase for nullability

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/App/TestConnectAppProtocolWithClientCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/ConnectAppProtocolWithClientCommand.cs

Check if client is available before trying to access the executable path.

b/335754832 Add missing check if client is available

---

sources/Google.Solutions.IapDesktop/App.config

Set supportedRuntime to 4.7.2 so that it matches the target framework

b/335763606 Set supportedRuntime to match target framework

---

sources/installer/Product.wxs

Add launch condition to enforce minimum Windows requirement, which is now Windows 10 or Server 2016.

b/335741487 Require Windows 10 or later

---

sources/Google.Solutions.Apis.Test/Auth/TestLoopbackCodeReceiver.cs
sources/Google.Solutions.Apis/Auth/LoopbackCodeReceiver.cs

Ignore irrevant requests such as requests to /favicon.ico. This fixes an issue where the listener prematurely stops for WFIF sign-in requests when the browser sends a /favicon.ico request,

b/335762873 Ignore irrelevant requests in loopback receiver

---

sources/Google.Solutions.IapDesktop/Program.cs

Update error handling code to use new TaskDialog
implementation.

b/316011380 Use new TaskDialog implementation

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestCredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceControlCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/App/TestConnectAppProtocolWithClientCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/ConnectAppProtocolWithClientCommand.cs

* Use struct to pass parameters
* Optionally show save-checkbox

b/336378025 Refactor credential dialog

---

sources/Google.Solutions.Apis.Test/Locator/TestAccessLevelLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestDiskTypeLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestImageLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestInstanceLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestLicenseLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestMachineTypeLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestNodeTypeLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestOrganizationLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestProjectLocator.cs
sources/Google.Solutions.Apis.Test/Locator/TestZoneLocator.cs
sources/Google.Solutions.Apis/Crm/ResourceManagerClient.cs
sources/Google.Solutions.Apis/Locator/OrganizationLocator.cs
sources/Google.Solutions.Apis/Locator/ProjectLocator.cs
sources/Google.Solutions.Apis/Locator/ResourceLocator.cs

* Use common base fixture for test
* Add OrganizationLocator

b/334718649 Refactor locator classes

---

sources/Google.Solutions.IapDesktop.Application/Windows/ProjectPicker/ProjectPickerDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ToolWindowViewBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Session/TestRdpCredentialEditor.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/RdpCredentialEditor.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/DownloadFileDialog.cs
sources/Google.Solutions.Mvvm/Binding/PropertiesView.cs
sources/Google.Solutions.Mvvm/Binding/ViewFactory.cs
sources/Google.Solutions.Mvvm/Binding/ViewServiceProviderExtensions.cs
sources/Google.Solutions.Mvvm/Binding/WindowFactory.cs
sources/Google.Solutions.Testing.Application/Mocks/MockDialog.cs

* Rename to IWindowFactory
* Extract interfaces for ITopLevelWindow

b/341201732 Consolidate window factory interfaces

---

sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/Properties/TestPropertiesInspectorWindow.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestCredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestInputDialog.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/TestToolWindow.cs
sources/Google.Solutions.IapDesktop.Application/Theme/ThemeService.cs
sources/Google.Solutions.IapDesktop.Application/Theme/Themes.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/InputDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/OptionsDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ProjectPicker/ProjectPickerDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ToolWindowViewBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/ToolWindows/DebugThemeView.cs
sources/Google.Solutions.IapDesktop.Extensions.Explorer/ToolWindows/Install/AboutCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceControlCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Rdp/TestRdpView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Ssh/TestDownloadFileDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Ssh/TestSshTerminalView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/RdpCredentialEditorFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/DownloadFileDialog.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Introduce specialized theme interfaces (ISystemDialogTheme etc) and inject them
* Remove ThemeService

b/341201732 Remove theme service

---

sources/Google.Solutions.IapDesktop.Core.Test/ObjectModel/TestService.cs
sources/Google.Solutions.IapDesktop.Core.Test/ObjectModel/TestServiceRegistry.cs
sources/Google.Solutions.IapDesktop.Core/ObjectModel/IServiceDecorator.cs
sources/Google.Solutions.IapDesktop.Core/ObjectModel/ServiceRegistry.cs

Extend existing logic for the Service<> decorator to support
custom service decorators

b/341201732 Service decorators

---

sources/makefile

Use regular signtool instead of the remote signtool for verifying signatures

b/341142757 Use signtool for verifying signatures

---

sources/Google.Solutions.IapDesktop.Application/ApplicationEventSource.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ViewBindingContext.cs

Include type of inner exception as 'source' parameter.

b/341806297 Track exception source for failed commands

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/Google.Solutions.IapDesktop.Extensions.Diagnostics.csproj
sources/Google.Solutions.IapDesktop.Extensions.Explorer/Google.Solutions.IapDesktop.Extensions.Explorer.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Google.Solutions.IapDesktop.Extensions.Session.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.Mvvm/Google.Solutions.Mvvm.csproj
sources/Google.Solutions.Mvvm/Theme/DpiAwareness.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs
sources/Google.Solutions.Testing.Application/Google.Solutions.Testing.Application.csproj

* Update to latest patched version of DockPanelSuite
* Enable WinForms .NET 4.7+ specific High-DPI features
* Remove redundant theme rules

b/342523478 Scale tool window controls

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Theme/VSThemeExtensions.cs
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/Google.Solutions.IapDesktop.Extensions.Diagnostics.csproj
sources/Google.Solutions.IapDesktop.Extensions.Explorer/Google.Solutions.IapDesktop.Extensions.Explorer.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Google.Solutions.IapDesktop.Extensions.Session.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.Testing.Application/Google.Solutions.Testing.Application.csproj

Disable menu item background customizations as it interferes with DPI scaling

b/343094844 Use patched version of DockPanelSuite

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Credentials/ShowCredentialsView.Designer.cs

* Fix icon size to prevent overlap
* Fix margin between label and textbox

b/343107025 Fix control alignment in ShowCredentialsView

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/Google.Solutions.IapDesktop.Extensions.Diagnostics.csproj
sources/Google.Solutions.IapDesktop.Extensions.Explorer/Google.Solutions.IapDesktop.Extensions.Explorer.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Google.Solutions.IapDesktop.Extensions.Session.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.Testing.Application/Google.Solutions.Testing.Application.csproj

Use patched version of DockPanelSuite that auto-scales the size of the AutoHideStrip

b/343106618 Update to patched version of DockPanelSuite

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Controls/RdpClient.ConnectionProperties.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Controls/RdpClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs

* Add connection setting
* Apply desktop, device scale factor to RDP session 
Ref #1100

b/343082958 Scale RDP session to match local DPI scaling settings

---

sources/Google.Solutions.Mvvm/Controls/ImageListExtensions.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs

* Scale imagelists, but only once
* Fix quality degradation

b/343587765 Auto-scale image lists

---

sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeView.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeView.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Auth/OAuthScopeNotGrantedView.Designer.cs
sources/Google.Solutions.Mvvm/Controls/CompositeForm.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs

* Scale label to fix text
* Fix border settings of OAutScopeNotGranted dialog to ensure auto-scaling

b/344701154 Scale controls on Authorize dialog

---

sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.cs

Use shorter text to avoid wrapping at high DPI

b/344702387 Use shorter button text

---

dependencies/sources/libssh2-cng/makefile

Update to latest stable version.

b/343795802 Update libssh2

---

sources/Google.Solutions.Mvvm/Controls/BindableListView.cs
sources/Google.Solutions.Mvvm/Controls/FileBrowser.cs
sources/Google.Solutions.Mvvm/Controls/ImageListExtensions.cs
sources/Google.Solutions.Mvvm/Controls/SearchableList.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs

* Avoid duplicate scaling of icons in DownloadDialog
* Avoid duplicate scaling of columns without maintaining cache

b/344702281 Refactor scaling logic for image lists, columns

---

sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/ActiveDirectory/JoinView.Designer.cs
sources/Google.Solutions.Mvvm/Binding/PropertiesView.Designer.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs

* Fix style for Join dialog to enable auto-scaling
* Add additional asserts in ruleset to ensure consistency

b/344702335 Fix border dialog styles

---

sources/Google.Solutions.Mvvm/Controls/BindableListView.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs

Scale column widths of static columns. This fixes an issue where the lists in the EventLog and Tunnels window weren't rescaled to match the High DPI settings.

b/345074336 Auto scale column width

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/Google.Solutions.IapDesktop.Extensions.Diagnostics.csproj
sources/Google.Solutions.IapDesktop.Extensions.Explorer/Google.Solutions.IapDesktop.Extensions.Explorer.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Google.Solutions.IapDesktop.Extensions.Session.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.Testing.Application/Google.Solutions.Testing.Application.csproj

Update DockPanelSuite dependency to pull in latest fix

b/360927073 Include tag in DockPanelSuite file versions

---

sources/makefile

Include `icu.dll` in code signing

b/333638160 Sign ICU Shim

---

sources/Google.Solutions.Terminal.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.Terminal.TestApp/Program.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Fix unhandled exception caused by minimizing the window

b/368413719 Handle resize even when window is minimized

---

sources/Google.Solutions.Terminal.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.Terminal.Test/Controls/TestVirtualTerminalBinding.cs
sources/Google.Solutions.Terminal.Test/Controls/TestVirtualTerminalColors.cs
sources/Google.Solutions.Terminal.Test/Controls/TestVirtualTerminalException.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.DesignProperties.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminalBinding.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminalColors.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminalEventArgs.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminalException.cs

Add "Virtual" prefix to better distinguish them from classes related to pseudo-terminal handling

b/345335944 Add prefix to terminal-related classes

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.Mvvm/Controls/ControlExtensions.cs
sources/Google.Solutions.Terminal/Controls/ClientBase.cs
sources/Google.Solutions.Terminal/Controls/ClientStatePanel.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.cs
sources/Google.Solutions.Terminal/Google.Solutions.Terminal.csproj

- Extract logic for showing connecting/disconnected screen to base class
- Handle edge case where network is lost during auto-reconnect

b/373208474 Extract logic for showing connecting/disconnected screen to base class

---

sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/IRdpSession.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/SessionCommands.cs
sources/Google.Solutions.Terminal.Test/Controls/TestRdpClient.cs
sources/Google.Solutions.Terminal/Controls/ClientBase.cs
sources/Google.Solutions.Terminal/Controls/PseudoTerminalClientBase.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.cs

Add session command to reconnect an existing RDP session. This is primarily intended for cases where the remote session timed out and shows a lock screen.
ref #1463

b/372785396 Reconnect existing RDP session

---

sources/Google.Solutions.Apis.Test/Compute/TestResourceMetadataExtensions.cs
sources/Google.Solutions.Apis/Compute/ResourceMetadataExtensions.cs

- Back off and retry when API returns 503
- Cleanup related unit tests

Retry metadata updates when service returns 503

---

sources/Google.Solutions.Terminal/Controls/SshHybridClient.cs

Activate and move focus to file browser when
re-executing menu command to open file browser.

b/379544825 Reactivate file browser

---

sources/Google.Solutions.Mvvm/Controls/BindableTreeView.cs
sources/Google.Solutions.Mvvm/Controls/FileBrowser.cs

Force current directory in tree view to be reloaded because new directories might have been added.

b/379952866 Invalidate tree view on refresh

---

sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

- Apply witdh based on system metrics
- Scale width based on DPI level

b/380166862 Size and scale terminal scrollbar

---

sources/Google.Solutions.Mvvm/Controls/FileBrowser.cs

Defer adding extra icon to image list until theme
has been applied.

b/380168466 Fix shell icons

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestSessionContextFactoryForSsh.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestSshSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Options/TestSshOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/SshParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/SshSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/SshOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/SshView.cs
sources/Google.Solutions.Terminal.Test/Controls/TestSshHybridClient.cs
sources/Google.Solutions.Terminal/Controls/SshHybridClient.cs
sources/installer/policies/IapDesktop.adml
sources/installer/policies/IapDesktop.admx

- Add group policy setting
- Disable file browser if group policy enforced

b/379334329 Add group policy setting for enabling/disabling SFTP

---

doc/site/sources/docs/group-policies-deployment.md

Update instructions to deploy IAP Desktop as LoB
app, which is simpler than deploying it as Win32
app.

b/380764171 Deploy as LoB app

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/SshContext.cs
sources/Google.Solutions.Platform.Test/Net/TestNetworkCredentialExtensions.cs
sources/Google.Solutions.Platform/Net/NetworkCredentialExtensions.cs

Emit telemetry event when authorizing a
new SSH or RDP credential.

b/379724736 Emit event when authorizing a new credential

---

sources/Google.Solutions.Apis/Client/RequestExtensions.cs
sources/Google.Solutions.Apis/Compute/ComputeEngineClient.cs
sources/Google.Solutions.Apis/Compute/WindowsCredentialGenerator.cs
sources/Google.Solutions.Apis/GoogleApiExceptionExtensions.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/MetadataAuthorizedPublicKeyProcessor.cs

- Handle bad-request errors like not-found errors
- Differntiate between generic bad-request errors and those caused by missing ActAs permissions

b/383187772 Handle bad-request errors returned by projects.get

---

sources/Google.Solutions.Common.Test/Util/TestExceptionExtensions.cs
sources/Google.Solutions.Common/Util/ExceptionExtensions.cs
sources/Google.Solutions.IapDesktop/Program.cs

Emit a telemetry event that contains a minimal
set of diagnostics information.

b/383012601 Emit event when showing ErrorDialog

---

sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Fixes an access violation caused by calling
TerminalSetCursorVisible after the terminal already received the WM_DESTROY message.

b/383208910 Skip subclass logic after WM_DESTROY

---

sources/Google.Solutions.IapDesktop/Program.cs

Add default parameter to indicate whether PSC is enabled

b/379724736 Add parameter for service route

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/DefaultAppProtocols/mysql-8.4.iapc
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/DefaultAppProtocols/psql-16.iapc
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/DefaultAppProtocols/psql-17.iapc

- Add Postgres 16, 17
- Update MySQL 8.1 to 8.4, because that's an LTS

b/383644946 Update default set of IAPC files

---

sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Add checks to prevent using the terminal when the
control has already processed a WM_DESTROY message.
This fixes an issue where a theme change caused an AV because the terminal was already semi-destroyed.

b/390046106 Avoid using terminal handle after WM_DESTROY

---

sources/Google.Solutions.Terminal/Google.Solutions.Terminal.csproj

Update dependencies to pull in latest NuGet packages for Terminal, ICU Shim

b/390040853 Update to Terminal 1.21.3231

---

doc/site/sources/mkdocs.yml

Make sure the navigation tabs remain visible when scrolling

b/391429523 Enable sticky navigation tabs

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Options/TestTerminalOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/TerminalSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/TerminalOptionsSheet.Designer.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/TerminalOptionsSheet.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Options/TerminalOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/SshView.cs
sources/Google.Solutions.Terminal.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.DesignProperties.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Add support for bracketed pasting in the terminal.
- Add setting to enable/disable bracketed pasting
- Extend subclass logic to apply bracketing for both,
keyboard accelerators and mouse-based pasting

b/391417764 Bracketed pasting

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Rdp/TestRdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/TestIapRdpUrlExtensions.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestIapRdpUrlSettingsStore.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Diagnostics/DiagnosticsCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/RdpView.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.ConnectionProperties.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.cs

* Add connection setting for redirecting the default audio input device to the remote VM.
* Rename resource sharing settings to be more consistent.

b/409123329 Redirect audio capture

---

doc/site/makefile

Used forked theme to ensure that the menu is visible on smaller screens/in smaller browser windows.

b/414889400 Optimize theme for smaller screens
