Plugin.Google.CloudIap/Gui/Plugin.cs
Plugin.Google.CloudIap/Integration/Project.cs
Plugin.Google.CloudIap/Plugin.Google.CloudIap.csproj
Plugin.Google.CloudIap/Util/LazyWithRetry.cs

If no valid gcloud configuration can be found, do not cache
the failure so that the user can run "gcloud auth login" and
retry the operation without having to restart RDCMan.

Reload gcloud configuration after failure

---

Google.Solutions.Compute/Extensions/AddMetadata.cs
Google.Solutions.Compute/Extensions/ResetWindowsUser.cs

When the user lacks the 'Service Account User' role,
password generation might fail.
Add error handling to detect this error more quickly and
show proper error message.
Change-Id: Ifed041137c10534aa634c5a2509d086c56fbc33b

Improve error handling for credential generation

---

Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs

When signing in via OAuth, we do not have the user's
email address. Therefore, use the local Windows username
as suggested username when generating credentials.

Use local Windows username as suggested username

---

Google.Solutions.Compute/Extensions/AddMetadata.cs
Google.Solutions.Compute/Extensions/ResetWindowsUser.cs

Sometimes, SetMetadata succeeds, but does not apply the change
until a few seconds later. Retry operation until the change has
been applied properly.

Wait for metadata changes to take effect

---

Google.Solutions.CloudIap.Plugin/Integration/ComputeEngineAdapter.cs

This is to fix https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/issues/22

Properly filter instances that have disks without licenses

---

Google.Solutions.Compute.Test/Auth/TestRegistryStore.cs
Google.Solutions.Compute/Auth/RegistryStore.cs

If credentials were stored in the registry with a different/
old DPAPI key, a CryptographicException was thrown.
Handle situation gracefully by ignoring undecypherable
credentials.

React gracefully if credentials cannot be decrypted

---

Google.Solutions.Compute.Test/Extensions/TestGetSerialPortOutputStream.cs
Google.Solutions.Compute.Test/Google.Solutions.Compute.Test.csproj
Google.Solutions.Compute/Extensions/GetSerialPortOutputStream.cs

Use start/next offsets of REST API to stitch the stream together.

Use 'next' positions for serial port logging

---

Google.Solutions.CloudIap.Plugin/Gui/PluginEventHandler.cs
Google.Solutions.Compute/Extensions/ResetWindowsUser.cs

* Check if instance exists and is running before reporting
a generic 'unauthorized' error.
* Make check for missing roles to reset passwords more precise.

Improve error messages

---

Google.Solutions.CloudIap.Plugin/Integration/DefaultTunnelingManager.cs
Google.Solutions.Compute.Test/Iap/TestSshRelayStreamReading.cs
Google.Solutions.Compute/Iap/SshRelayStream.cs

Ignore unrecognized tags to future-proof the implementation.
Newer versions of the protocol might introduce new message tags
which should not cause the implementation to break.

Ignore unrecognized message tags

---

Google.Solutions.CloudIap.Plugin/Gui/ProjectPickerDialog.Designer.cs
Google.Solutions.CloudIap.Plugin/Gui/ProjectPickerDialog.cs

Assume that the entered text is a project ID, even if it is
not suggested by the autocompleter.
Also, fix a race condition where two error dialogs might be
displayed in case an invalid project ID is provided.

Project Picker: Allow pasting/quick entering of project ID

---

Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
Google.Solutions.IapDesktop.Application.Test/Util/TestAuthorizationExtensions.cs
Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
Google.Solutions.IapDesktop.Application/Util/AuthorizationExtensions.cs
Google.Solutions.IapDesktop.Application/Windows/ProjectExplorer/ProjectExplorerWindow.cs

Derive the suggested Windows username from the email address
used for signing in. This aligns the behavior with the
Cloud Console's behavior.

Derive username from email address

---

Google.Solutions.IapDesktop.Application/Windows/ProjectExplorer/ProjectExplorerWindow.cs
Google.Solutions.IapDesktop.Application/Windows/SerialLog/SerialLogService.cs
Google.Solutions.IapDesktop.Application/Windows/SettingsEditor/SettingsEditorWindow.cs
Google.Solutions.IapDesktop.Application/Windows/ToolWindow.cs
Google.Solutions.IapDesktop.Application/Windows/TunnelsViewer/TunnelsWindow.cs

When window is activated again, avoid resetting
its state to the default.

Maintain window position when activated again

---

Google.Solutions.Compute.Test/Env/InstanceAttribute.cs

Embed Kokoro job type in machine hash/VM name so that different types of jobs do not share the same VMs.

Embed job type in machine hash

---

Google.Solutions.IapDesktop.Application/Services/Windows/RemoteDesktop/RemoteDesktopPane.Designer.cs
Google.Solutions.IapDesktop.Application/Services/Windows/RemoteDesktop/RemoteDesktopPane.cs

If the user minimizes from within full-screen mode, the control does not send any events that could be used to prevent the "white screen" issue. 
As the events of minimizing are unclear in case of a multi-RDP app anyway, the easiest solution is to hide the button.
This is to fix #87.

Hide Minimize button in full-screen mode

---

Google.Solutions.Compute.Test/Env/InstanceAttribute.cs

Change-Id: Ib18a803e199724e05236b3dc6976b3831c3e53cb

Use n1-standard-2, -1 is too slow to be reliable in tests

---

Google.Solutions.IapDesktop.Application/Services/Windows/RemoteDesktop/RdpExceptions.cs
Google.Solutions.IapDesktop.Application/Services/Windows/RemoteDesktop/RemoteDesktopPane.cs
Google.Solutions.IapDesktop/Program.cs

Reduce unnecessary stress on RDP control:
* Avoid resizing the RDP control to (0, 0) when the window is minimized
* Ignore resizing the RDP control when the size has not really changed
Improve error message for disconnects
* Incorporate message provided from control (if any) into exception message.
This is to to address #111

Reduce unnecessary stress on RDP control

---

Google.Solutions.Common/Auth/GoogleAuthAdapter.cs

* Include command to re-enable http.sys in message.
* Because re-enabling a driver requires admin privileges, the
application cannot initiate this by itself.
This is to fix #96.

Provide descriptive error message when http.sys is disabled.

---

Google.Solutions.IapDesktop.Application/Services/Windows/RemoteDesktop/RemoteDesktopPane.cs

This fixes an issue where the pane thought the control
was reconnecting, although it was not, which in turn
caused the Full Screen menu item to be disabled.

Ignore redundant resize event

---

Google.Solutions.IapDesktop.Application/Services/Windows/FlatVerticalTabControl.cs

Avoid creating a temporary Image because it wastes
plenty of memory resources.

Fix tab drawing efficiency

---

Google.Solutions.IapDesktop.Application/Services/Persistence/ConnectionSettingsRepository.cs

When using IAP, this authentication level is almost
guaranteed to not work, unless the server's certificate
has been issued for the CN "localhost". Therefore, hide
it in the UI.

Hide "RequireServerAuthentication" option

---

sources/Google.Solutions.IapDesktop.Application/Services/Windows/RemoteDesktop/RemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Application/Services/Windows/UnsafeNativeMethods.cs

Use `IMsRdpClient9::UpdateSessionDisplaySettings` to dynamically adjust resolution whenever possible. Fall back to `Reconnect` when client or server do not support dynamic resolution changes.
This is to fix #115 and #202

Adjust resolution without reconnecting

---

sources/Google.Solutions.IapDesktop.Extensions.Activity/History/InstanceSetHistoryBuilder.cs

This fixes an issue where currently running SPLA instances
were missed by the report because their synthetic placement
was not captured by the date selection filter.

Use consistend end date, avoid DateTime.Now

---

sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerTrackingToolWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/ToolWindow.cs

This fixes an issue where an auto-hide tool window closes
and later does not update properly once it becomes visible
again.

Force UserVisibilityState event raise when window is shown

---

sources/Google.Solutions.Common/ApiExtensions/Instance/ResetWindowsUser.cs

Old versions of the OS agent wrongly escaped slashes with backslashes,
probably as a result of a bug. The backslashes caused the modulo search to
fail, resulting in a timeout.
This is to fix #27.

#27: Ignore backslashes in user reset-response

---

sources/Google.Solutions.IapDesktop.Extensions.Activity/Services/Adapters/AuditLogStorageSinkAdapter.cs

This is a workaround for b/170388158.

b/170453002: Ignore audit events that lack a methodName

---

sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Lifecycle/ResumeInstanceEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Lifecycle/SuspendInstanceEvent.cs

Semantics of suspend and resume events was mixed up, leading to suspensions being ignored in instance history

b/171293988 Fix handling of suspend/resume events in reporting

---

sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/History/TestInstanceHistoryBuilder.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Views/UsageReport/TestReportInstancesTabViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Views/UsageReport/TestReportNodesTabViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/History/InstanceHistoryBuilder.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/History/InstanceSetHistoryBuilder.cs

If an instance is currently running, but no Start event is observed,
extend its placement to cover the entire analysis period. This
ensures that the instance is properly counted for in histograms.

b/171293988 Extend synthetic placements to cover analysis period

---

sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

This fixes a null reference exception when a command is
invoked via a shortcut (as opposed to opening the menu).
This is to fix #311.

Set context on initialization

---

sources/Google.Solutions.IapDesktop.Application/Views/Properties/PropertiesInspectorWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/EventLog/EventLogWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/SerialOutput/SerialOutputWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Os/Views/PackageInventory/PackageInventoryWindow.cs

This fixes an issue where the window title was briefly
updated to show the VM name and then switched back to
showing a generic window title.

b/174133695 Update window title when selection changes

---

sources/Google.Solutions.IapDesktop.Extensions.Rdp/Views/Credentials/CredentialsService.cs

When the VM is domain-joined, the "." ensures that the logon
is attempted using the local user instead of a domain user.

Force local login when using generated credentials

---

sources/Google.Solutions.IapDesktop.Extensions.Rdp/Views/RemoteDesktop/RemoteDesktopPane.Designer.cs

Indicate that a disconnect can not only happen because of
a timeout, but also for other reasons (like one user kicking
out another).

Fix wording on reconnect screen

---

dependencies/makefile
dependencies/vcpkg-ports/libssh2/portfile.cmake

* Remove _DEV suffix from version string
* Use version numbers larger than nuget.org packages

Update dependency versions

---

sources/Google.Solutions.Common/Util/ExceptionExtensions.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestComputeEngineAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/ComputeEngineAdapter.cs

Testing permissions requires the 'compute.instances.list'
permission. If the user does not hold this permission, fail
open.
This fixes an issue where connecting to an instance by URL
failed if the user only had the 'iap.tunnelInstances.accessViaIAP'
perission (#365).

b/177117188 Fail open if permission check fails

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/SshWorkerThread.cs

Instead of blocking the UI until the SSH worker
thread is done, tear down UI and stop passing
events to the (disposed) UI.

Fix UI hang when connection handshake hangs

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestAuthorizedKeyService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Ssh/AuthorizedKeyService.cs

When checking if the key has been pushed before,
ignore expired entries in the key set and push
again if necessary.

Ignore expired keys

---

dependencies/makefile
dependencies/vtnetcore-patches/0001-Handle-OSC-sequences-with-empty-text-parameters.patch

- Extend makefile to apply patch pre-build
- Increment tag

Add patch to fix OSC sequences with empty text parameters

---

sources/Google.Solutions.Ssh.Test/Native/TestSshAuthenticatedSession.cs
sources/Google.Solutions.Ssh/Native/SshAuthenticatedSession.cs
sources/Google.Solutions.Ssh/Native/UnsafeNativeMethods.cs

During finalization, it's possible that a channel handle is freed
after the associated session has been freed already. Detect
this situation and prevent the free'ing of the channel handle
as it would cause an access violation.

Do not free channel if session has been freed already

---

sources/Google.Solutions.IapDesktop.Application/Services/UpdateService.cs

Ensure that we always download the MSI file, even if there is another
package that's listed first (the API seems to be listing alphabetically).

Download MSI, even if it's not the first asset

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminal.cs

This fixes an issue where the caret was off by one pixel
and did not properly align with a text selection.

Use ceiling when calculating caret position

---

sources/Google.Solutions.IapDesktop.Application/Views/ToolWindow.cs

Only consider Shift+Esc as shortcut if window
is floating or docked. This fixes an issue where
Shift+Esc closes a terminal window even if it was
supposed to be a keytroke to be sent to the server.

b/184619387 Ignore Shift+Esc shortcut in documentate

---

sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Views/SerialOutput/TestAnsiTokenReader.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Views/SerialOutput/AnsiTokenReader.cs

This fixes an issue where some logs (particularly from
Linux VMs) caused an 'unrecognized escape sequence' error.

Consume character set selection-sequences in serial log

---

sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

This fixes an issue where icons were missing for
certain commands in the Desktop menu.

Use ImageAndText display style for Desktop menu

---

sources/Google.Solutions.IapDesktop.Extensions.Os/Views/PackageInventory/PackageInventoryViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Os/Views/PackageInventory/PackageInventoryWindow.cs

This fixes an issue where the window shows the default "PackageInventoryWindow"
title when the initial load is slow.

b/185888130 Set window title before loading model

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Options/TerminalOptionsControl.cs

Although rare, the FontDialog can throw an exception
if a font cannot be loaded for some reason.

Catch exceptions from FontDialog

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/ProjectModel/TestProjectModelService.cs
sources/Google.Solutions.IapDesktop.Application/Services/ProjectModel/ProjectModelService.cs

This fixes an issue where connecting to an instance by URL
failed when the enclosing project had not previously been
loaded.

Do not attempt to load instance data when enclosing project not loaded

---

dependencies/makefile
dependencies/vcpkg-ports/libssh2/portfile.cmake

* Patch resource file to include build version of libssh2, openssl
* Update openssl to latest 1.1.1k

b/183477875 Update dependencies, embed build number in version resource

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshAuthenticationPromptViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshAuthenticationPromptViewModel.cs

This is to prevent the description text from extending
beyond window bounds.

Add newlines to 2SV description text

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs

If tracing is enabled, add a command to the
context menu that lets a user copy all sent data
for diagnostic purposes

b/187931875 Add command to copy sent data (if tracing is enabled)

---

sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugFocusWindow.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugFocusWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/Diagnostics/DebugFocusWindow.resx
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/MsRdpClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.Designer.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

When the RDP control loses focus and you later click into the
control again, the control does not re-gain focus. Fix this
default behavior by forcing the focus back on the control
whenever we see a WM_MOUSEACTIVATE message.
This addresses #490

Force focus back to RDP control when activated by mouse

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/MsRdpClient.cs

Re-focusing interferes with certain operations such
as resizing windows in Remote Desktop

Avoid re-focusing if control already has focus

---

dependencies/makefile
dependencies/vtnetcore-patches/0005-Detect-key-modifier-options-XTMODKEYS.patch

Patch vtnetcore:
* Add sequence handler for:
- modifyKeyboard
- modifyCursorKeys
- modifyFunctionKeys
- modifyOtherKeys
* Extend VirtualTerminalController to track mode
The KeyPress logic is unchanged, i.e. the key modifier options are
only detected, but not applied.

Add vtnetcore patch for detecting key modifiers

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminalKeyHandler.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminalKeyHandler.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminalKeyTranslation.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj

* Use custom key translation table instead of relying on vtnetcore to do key translation
* Remove workarounds that were required for using vtnetcore key translations
* Extend unit tests to cover relevant key translations
This lays the groundwork for #482

b/189199398 Use custom key translation table

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminalKeyHandler.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminalKeyHandler.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminalKeyTranslation.cs

* Use xterm's translation for function keys instead of PuTTY's (legacy) ones
* Add translation table for 'modifyOtherKeys = 1' mode
* Add tests
This addresses #482

b/189199398 Extend keyboard translations to support modifyOtherKeys mode

---

sources/Google.Solutions.IapDesktop.Application/Controls/BindableTreeView.cs

Suspend redrawing while updating nodes
to reduce flicker and vertical scrolling.
This is to address #512

b/191854140 Suspend redrawing while updating Project Explorer nodes

---

dependencies/libssh2.targets
dependencies/makefile
dependencies/vcpkg-triplets/libssh2-x64-windows-mixed.cmake

* Update to latest vcpkg tag
* Add x64 triplet for libssh2
* Extend nuspec to include x86 and x64 DLLs, PDBs
* Change targets file to copy architecture-specific files
* Bump tag to 18

b/192170307 Include x86 and x64 DLLs, PDBs in libssh2 NuGet package

---

sources/Google.Solutions.Common/Auth/GoogleAuthAdapter.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

If an admin changes the access level for the app (in the Admin Console),
then it's possible that some of the requested scopes haven't been granted.
This can cause subsequent API calls to fail.

Verify that all requested scopes are granted

---

dependencies/makefile
dependencies/vtnetcore-patches/0005-Fix-throw-statement-to-avoid-cascading-exception.patch

Fix `throw` statement to avoid cascading exception
Throw proper exception when no handler has been registered
for a DCS sequence. This fixes an issue where throwing
an exception could cause another exception if the first
parameter has not been extracted yet.
This addresses #545

Add patch: Fix throw statement to avoid cascading exception

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/packages.config
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/packages.config
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh.Test/packages.config
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/packages.config

* Update vtnetcore, libssh2 to .19 to ensure that vtnetcore
includes the fix for cascading exceptions thrown in DCS handling.
* Add unit tests to verify presence of patch

Update dependencies to include vtnetcore fix

---

sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs

This fixes an issue where right after startup, all
toolbar buttons and context menu commands were enabled.

Initialize toolbar, context menu to only show commands for root node

---

sources/Google.Solutions.IapDesktop/Program.cs

* Enable TLS 1.3 on Windows 11/Windows Server 2022 as these versions officially
support TLS 1.3 in WinHTTP and SChannel.
* Use TLS 1.2 on Windows 10 and below.
* Continue to allow fallback to TLS 1.1 as some proxy servers might not support
TLS 1.2/1.3 yet.
This addresses #544

b/197197943 Enable TLS 1.3 on Windows 11/Windows Server 2022

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestCertificateStoreAdapter.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/SecureConnect/TestChromeCertificateSelector.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/SecureConnect/TestChromeMatchPattern.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/SecureConnect/TestSecureConnectEnrollment.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/CertificateStoreAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/SecureConnect/ChromeCertificateSelector.cs
sources/Google.Solutions.IapDesktop.Application/Services/SecureConnect/ChromeMatchPattern.cs
sources/Google.Solutions.IapDesktop.Application/Services/SecureConnect/SecureConnectEnrollment.cs
sources/Google.Solutions.IapDesktop.Application/Services/Settings/ApplicationSettingsRepository.cs

Allow selecting a custom client certificate in place of the default
EV-provisioned certificate. The filter uses a syntax derived from
Chrome's AutoSelectCertificateForUrls filter syntax.

b/193758410 Client certificate selection

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Adapter/OsLoginAdapter.cs
sources/Google.Solutions.IapTunneling/Iap/SshRelayListener.cs

This fixes an issue where a lost server connection (or failed
SSH keepalive) did not cause the SSH terminal pane to show
the "Session disconnected" panel.

b/191138997 Close local connection when server connection is closed

---

sources/build.bat
sources/makefile

BOM needs to be removed regardless of whether tests
suceeded or failed. Previously, the BOM was only removed
if tests succeeded.

Unconditionally remove BOM from sponge_log.xml

---

sources/Google.Solutions.Common.Test/ApiExtensions/Instance/TestAddMetadata.cs
sources/Google.Solutions.Common.Test/ApiExtensions/Request/TestExecuteAsStreamExtensions.cs
sources/Google.Solutions.Common.Test/Assert.cs
sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestComputeEngineAdapter.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestResourceManagerAdapter.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestWindowsCredentialAdapter.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Integration/TestJobService.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/ProjectModel/TestProjectModelService.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Settings/TestAuthSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/Adapters/TestAuditLogAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/Adapters/TestAuditLogStorageSinkAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Services/Adapters/TestStorageAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Os.Test/Services/Inventory/TestInventoryService.cs
sources/Google.Solutions.IapDesktop.Extensions.Os.Test/Views/InstanceProperties/TestInstancePropertiesInspectorViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestAuthorizedKeyService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestOsLoginService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestSshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Tunnel/TestTunnelBrokerService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Tunnel/TestTunnelService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Credentials/TestCredentialPrompt.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Credentials/TestCredentialsService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshAuthenticationPromptViewModel.cs
sources/Google.Solutions.IapTunneling.Test/Iap/TestHttpOverIapDirectTunnel.cs
sources/Google.Solutions.IapTunneling.Test/Iap/TestSshRelayProber.cs
sources/Google.Solutions.IapTunneling.Test/Iap/TestSshRelayStreamReading.cs
sources/Google.Solutions.IapTunneling.Test/Iap/TestSshRelayStreamWriting.cs
sources/Google.Solutions.Ssh.Test/Native/TestSshSession.cs
sources/Google.Solutions.Ssh.Test/TestSshShellConnection.cs

- Split into ExceptionAssert and PropertyAssert
- Use naming scheme that matches NUnit's classes

Rename AssertEx class

---

sources/Google.Solutions.Common/Google.Solutions.Common.csproj
sources/Google.Solutions.Common/Net/HttpClientHandlerExtensions.cs
sources/Google.Solutions.Common/Net/RestClient.cs
sources/Google.Solutions.IapDesktop.Application.Test/Services/Authorization/TestSignInAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/ClientServiceInitializer.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/ComputeEngineAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/ResourceManagerAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/SignInAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Services/Adapters/AuditLogAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Services/Adapters/StorageAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Adapter/OsLoginAdapter.cs
sources/Google.Solutions.IapDesktop/Windows/MainFormViewModel.cs

Use mTLS for fetching tokens and OIDC userinfo when
a device certificate exists.

b/214344362 Use mTLS for sign-in

---

sources/Google.Solutions.IapDesktop.Application/Views/DocumentWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ShellExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs

Changing to Ctrl + Alt + F11, which
* works on notebook keyboards (which lack a Break key)
* is more consistent with the F11 shortcut to enter full-screen

b/216743374 Change shortcut for leaving full-screen RDP

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ConnectionSettings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs

* Keep default (only pass shortcuts in full-screen mode)
* Add setting to change behavior (always, never)
This addresses #607.

b/218679437 Add setting to control Windows shortcut handling

---

sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Events/Access/TestSetCommonInstanceMetadataEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Access/ModifiedMetadata.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Access/SetCommonInstanceMetadataEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Events/Access/SetMetadataEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Activity/Google.Solutions.IapDesktop.Extensions.Activity.csproj

* Extract modofied keys from setCommonInstanceMetadata event
(introduced in b/135056849)
* Adapt event message based on whether 'ssh-keys' was found

b/210366612 Detect project-wide SSH key pushes in event log

---

sources/Google.Solutions.Common.Test/Integration/TestProject.cs
sources/Google.Solutions.IapDesktop.Application/Views/Dialog/ExceptionDialog.cs

Enable TLS 1.2 before test execution starts. Some endpoints 
don't support TLS 1.1 anymore.

Enable TLS 1.2 for integration tests

---

sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.Common/Google.Solutions.Common.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Extensions.Activity.Test/Google.Solutions.IapDesktop.Extensions.Activity.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Activity/Google.Solutions.IapDesktop.Extensions.Activity.csproj
sources/Google.Solutions.IapDesktop.Extensions.Os.Test/Google.Solutions.IapDesktop.Extensions.Os.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Os/Google.Solutions.IapDesktop.Extensions.Os.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj
sources/Google.Solutions.IapTunneling.Test/Google.Solutions.IapTunneling.Test.csproj
sources/Google.Solutions.IapTunneling/Google.Solutions.IapTunneling.csproj
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj

Change target framework to 4.6.2 as 4.6.1 will be deprecated
on April 26, 2022.

b/229048026 Target .NET 4.6.2

---

sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.Common.Test/Threading/TestSingleThreadSynchronizationContext.cs
sources/Google.Solutions.Common/Google.Solutions.Common.csproj
sources/Google.Solutions.Common/Threading/SingleThreadSynchronizationContext.cs
sources/Google.Solutions.Common/Threading/SynchronizationContextExtensions.cs

- Add SingleThreadSynchronizationContext, a context
that executes callback on a designated thread
- Add SynchronizationContextExtensions to make
SynchronizationContexts easier to use with async

Add SynchronizationContext helper classes

---

sources/Google.Solutions.IapDesktop/Windows/Resources.resx
sources/Google.Solutions.Ssh.Test/TestSshShellConnection.cs

Display an error messagen when the redirect URI
contains an 'error' parameter, indicating that the
authorization failed or has been cancelled.

b/229066583 Show error page when OAuth flow was cancelled

---

sources/Google.Solutions.IapDesktop.Application/Controls/ListViewExtensions.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Util/ClipboardUtil.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshTerminalPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/ShowCredentialsDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs

If the clipboard is busy, silently ignore the copy/
paste operation. This is in line with how most Windows
applications handle such errors.

b/229769118 Ignore copy/paste if clipboard is busy

---

sources/Google.Solutions.Ssh/Native/SshSession.cs
sources/Google.Solutions.Ssh/Native/SshSftpFileChannel.cs
sources/Google.Solutions.Ssh/RemoteConnection.cs
sources/Google.Solutions.Ssh/RemoteFileSystemChannel.cs

Although the operstions are done as blocking, they
could might time out if the connection speed is low.
Disable timeout during upload/download and restore
afterwards.

b/227935260 Disable timeout for file upload/download operations

---

sources/Google.Solutions.Ssh.Test/Native/TestSshSftpFileChannel.cs
sources/Google.Solutions.Ssh/Native/SshSftpFileChannel.cs
sources/Google.Solutions.Ssh/Native/UnsafeNativeMethods.cs
sources/Google.Solutions.Ssh/RemoteFileSystemChannel.cs

libssh_sftp_write doesn't guarantee that the entire
buffer is written. Therefore, repeat writes if
necessary.

Handle partial SFTP writes

---

sources/Google.Solutions.Ssh/RemoteFileSystemChannel.cs

Use 32000 byte buffers, corresponding to the maximum
size supported by libssh2.

b/227935260 Increase buffer for SFTP transfers

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs

This fixes an issue where the pane closes, and the next
open pane isn't properly invalidated/redrawn.
Addresses #673.

Force focus back to main window before closing RDP pane

---

sources/Google.Solutions.IapDesktop.Application/Views/Dialog/ConfirmationDialog.cs
sources/Google.Solutions.IapDesktop.Application/Views/Dialog/TaskDialog.cs
sources/Google.Solutions.IapDesktop.Application/Views/Dialog/UnsafeNativeMethods.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs

- Use TaskDialog instead if MessageBox
- Truncate overly long file names in SFTP
confirmation message

b/231083798 Use TaskDialog for confirmation

---

sources/Google.Solutions.IapDesktop.Application/Util/SingletonApplicationBase.cs

If creating or communicating with the named pipe fails,
revert to launching a new instance (instead of bailing
out).

b/232821184 Handle named pipe errors more gracefully

---

sources/Google.Solutions.IapDesktop.Application.Test/Util/TestSingletonApplicationBase.cs
sources/Google.Solutions.IapDesktop.Application/Util/SingletonApplicationBase.cs

Mutex names are case-sensitive, but pipe names aren't.
Normalize casing to prevent a situation where a second
instance can claim the mutex (because it uses a different
casing) but then can't open another pipe server because
the pipe name is taken (with a different casing).
Remove retry-logic as it shouldn't be required anymore
with this fix in place.

b/232821184 Normalize casing for mutex and named pipe

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/ProjectModel/TestProjectModelService.cs
sources/Google.Solutions.IapDesktop.Application/Services/ProjectModel/ProjectModelService.cs

When loading the root node, eagerly load zones
so that network calls can be made in parallel.

b/239994142 Load/reload zones in parallel

---

sources/Google.Solutions.Ssh.Test/Native/TestSshShellChannel.cs
sources/Google.Solutions.Testing.Common/Integration/InstanceAttribute.cs

The debian-9 image family has been deprecated,
so use debian-11 instead.

Use Debian 11 for test VMs

---

sources/Google.Solutions.IapDesktop.Application.Test/ObjectModel/Commands/TestCommandContainer.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/ObjectModel/Commands/CommandContainer.cs
sources/Google.Solutions.IapDesktop.Application/ObjectModel/Commands/ObservableCommandContextSource.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerWindow.cs
sources/Google.Solutions.IapDesktop.Application/Views/ToolWindow.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Rdp/TestRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Ssh/TestSshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/TestSessionPaneBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Rdp/RdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ShellExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Ssh/SshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SessionPaneBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/TerminalPaneBase.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

* Change XxxConnectionService to return session objects
* Use the same command set for the Session (main) menu and the
tab context menu
* Hide default 'Close' menu item when custom context commands set

b/240100649 Surface session commands in tab context menu

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/TerminalFont.cs

According to the documentation, StringFormat.GenericTypographic
should always use Near alignment, but occasionally it doesn't and
uses Center instead.
Explicitly set text alignment to prevent misligned text in the
terminal.

b/241178774 Explicitly set text alignment

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/ProjectModel/TestProjectModelService.cs
sources/Google.Solutions.IapDesktop.Application/Services/ProjectModel/ProjectModelService.cs

When pre-loading zones, ignore inaccessible projects. This
ensures that inaccessible projects are still shown, but don't
interfere with the laoding/caching of other projects.

b/241023620 Ignore inaccessible projects during pre-load

---

sources/installer/Product.wxs

Allow non-elevated installs on Windows Server if the 
`DisableMSI` and `DisableUserInstalls` policies indicate that
per-user installs are allowed.

b/239319139 Allow installation on Windows Server if policy set

---

sources/Google.Solutions.Common.Test/Util/TestExceptionExtensions.cs
sources/Google.Solutions.Common/Util/ExceptionExtensions.cs

Unwrap nested exceptions to avoid showing error messages like
"One or more errors have occured".

Unwrap nested AggregateExceptions, InvocationTargetExceptions

---

sources/Google.Solutions.Mvvm.Test/Commands/TestCommandContainer.cs
sources/Google.Solutions.Mvvm/Commands/CommandContainer.cs

When a nested command fails, raise the exception event
on the topmost container.

b/238571887 Pass exception events to topmost container

---

sources/Google.Solutions.IapDesktop/Program.cs

Make sure that the service can access dependent services, 
in particular the HelpService.

b/244119260 Move ExceptionDialog back to window/workflow layer

---

sources/installer/Product.wxs

This is to prevent the registry path from containing a redundant
HKEY_CURRENT_USER.

b/244264576 Remove 'HKEY_CURRENT_USER' from component key path

---

sources/Google.Solutions.IapDesktop.Application/Views/Dialog/ExceptionDialog.cs

TaskDialogIndirect can fail spuriously, typically with a 0x80070715 error (The specified resource type cannot be found in the image file). If that happens, fall back to using a classic MessageBox.

b/244620235, b/239776121 Fall back to MessageBox if TaskDialog fails

---

sources/Google.Solutions.IapDesktop.Application/Services/ThemeService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPane.cs

* Set float window properties after creation
* Use custom float window factory to fix faulty handling of the Minimize button in DockPanelSuite
* Consider float windows when setting context for session menu/commands
Cf #712

b/244659106 Use sizable, minimizable float window

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/TerminalPaneViewModelBase.cs

Avoid resizing the virtual terminal when the window size changes to (0,0). This ensures that the terminal buffer is properly maintained when the window is later restored/maximized.

b/248087823 Avoid resizing virtual terminal when window minimized

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestNetworkOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/NetworkOptionsViewModel.cs

Trim whitespace from host name and URL before applying changes so that accidentally copied whitespace doesn't cause issues.

b/249433546 Trim host name, URL for proxy settings

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshTerminalPane.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshTerminalPaneViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs

Extend error message to indicate that the authentication error might be caused by rsa-ssh being disallowed. Only show the extended error messagen when the user is actually using RSA.

b/248097454 Improve error when SSH authentication fails

---

sources/makefile

Package environment variables (incl. $env:WIX) are not available during signing, but the path is also unnecessary as the DLLs are located in the same folder as the binary.

Remove path from extension argument

---

sources/Google.Solutions.IapDesktop.Application.Test/Host/TestProfile.cs
sources/Google.Solutions.IapDesktop.Application/Host/Profile.cs

Check prefix of key name to ignore other keys, including the "Installer" key created by the installer package.

b/249900045 Ignore non-profile keys when listing profiles

---

sources/Google.Solutions.IapDesktop.Application/Services/UpdateService.cs

Check every 10 (instead of 7) days to pace update rollouts.

b/244787438 Increase time between update checks

---

.gitignore
sources/build.ps1

Auto-generate nuget.config and configure source
mappings so that packages from the local dependency 
feed are always preferred over nuget.org packages.

b/253120524 Use NuGet package source mappings

---

dependencies/sources/dockpanelsuite/makefile
dependencies/sources/dockpanelsuite/patches/0001-Refresh-focus-when-active-pane-has-changed.patch

This fixes an issue with the focus of tabs: When the window
is tiled (multiple panes) and one of the panes contains an RDP
pane, then the clicking the tab of RDP pane doesn't move the focus.
This patch refreshes the focus more aggressively to compensate 
for ActiveX control interfering with focus management.

b/249910962 Add patch for refreshing focus when active pane has changed

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Controls/VirtualTerminal.cs

CRLF line endings were previously converted to NL. That works in most terminals and editors (incl. vim), not in others (like older nano versions).
Convert line endings to CR instead to comply with
how other terminals behave and to be compatible with nano.

b/253777656 Fix line endings when pasting text

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs

During an unorderly disconnect, it's possible that the RCW is separated too early, causing `Connected` to throw an exception.

b/251163460 Catch exception when checking connection status

---

sources/Google.Solutions.IapDesktop.Application.Test/Google.Solutions.IapDesktop.Application.Test.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Util/TestFilename.cs
sources/Google.Solutions.IapDesktop.Application/Google.Solutions.IapDesktop.Application.csproj
sources/Google.Solutions.IapDesktop.Application/Util/Filename.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSftpFileSystem.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SftpFileSystem.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/SshTerminal/SshTerminalPaneViewModel.cs

* Avoid passing incompliant filenames to Shell API
* Use escaped filename for creating local file
Addresses #828

b/257378836 Handle Win32-incompliant filenames

---

sources/Google.Solutions.IapDesktop/Windows/MainForm.Designer.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

Decrease minimum window size so that it's a
quarter of 1080p (half height, half width, minus
taskbar).
Cf. #841

b/260624119 Use quarter-1080p as minimum size

---

sources/Google.Solutions.IapDesktop.Application.Test/Services/Authorization/TestAuthorization.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/SignInAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Authorization/AppAuthorization.cs

Fix reauth credential swapping approach: Instead of wrapping the credential,
update the (User) credential in-place. This ensures that existing clients (which
hold on to UserCredential objects) use the updated credential after reauth.

b/264818000 Ensure clients use new token after reauth

---

sources/Google.Solutions.IapDesktop.Application.Test/Util/TestSingletonApplicationBase.cs
sources/Google.Solutions.IapDesktop.Application/Util/SingletonApplicationBase.cs

Fix an issue where 2 instances of IAP Desktop running in 2 different sessions used different Mutexes (because of local namespacing), but the same pipe name, causing a "All pipe instances are busy" error.

b/270097766 Incorporate session ID into mutex, pipe name

---

sources/Google.Solutions.Common.Test/Diagnostics/TestDumpObjectExtensions.cs
sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.Common/Diagnostics/DumpObjectExtensions.cs
sources/Google.Solutions.Common/Google.Solutions.Common.csproj
sources/Google.Solutions.IapDesktop.Application.Test/Services/Adapters/TestGithubAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/ExternalRestAdapter.cs
sources/Google.Solutions.IapDesktop.Application/Services/Adapters/GithubAdapter.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Connection/TestRdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Connection/TestRdpCredentialCallbackService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/ConnectionSettings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/ConnectionSettings/TestIapRdpUrlConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Credentials/TestSelectCredentialsWorkflow.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Data/RdpSessionParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Google.Solutions.IapDesktop.Extensions.Shell.csproj
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Connection/RdpConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Connection/RdpCredentialCallbackService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Connection/SshConnectionService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ConnectionSettings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Credentials/SelectCredentialsWorkflow.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Diagnostics/DiagnosticsCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/ConnectInstanceCommand.cs
sources/scripts/credential-callback-server.ps1

Add support for `CredentialCallbackUrl` parameter in iap-rdp/// URLs. When set,
credentials are obtained from the specified URL. This is to allow portals to
pass RDP credentials to clients without exposing them in a iap-rdp/// URL.
Ref #872

b/274025818 RDP credential callback

---

sources/Google.Solutions.Common/Net/RestClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Services/Connection/TestRdpCredentialCallbackService.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Connection/RdpCredentialCallbackService.cs

* Extend RestClient to detect timeouts
* Use shorter default timeout
* Show proper error message when credential callback times out

b/274025818 Apply custom timeout for REST requests

---

sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/RemoteDesktop/TestRemoteDesktopViewWithGroupPolicies.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestConnectCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestConnectInstanceComand.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestConnectRdpUrlCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/Session/TestInstanceSessionBroker.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Views/SshTerminal/TestSshTerminalView.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/ShellExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/ConnectCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/ConnectInstanceCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/ConnectRdpUrlCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/SessionBroker.cs
sources/Google.Solutions.Testing.Application/Views/TestMainForm.cs

Let session broker maintain and add context commands. This ensures that all 
sessions receive a context menu, regardless of how the were created.

b/274050182 Sessions launched via URL lack context menu

---

sources/Google.Solutions.IapDesktop.Extensions.Management/Services/ActiveDirectory/DomainJoinService.StartupScript.ps1
sources/Google.Solutions.IapDesktop.Extensions.Management/Services/ActiveDirectory/DomainJoinService.cs

Avoid using PKCS#1.5 padding as it's no longer recommended.

b/274998103 Use RSAES-OAEP for domain credentials

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectExplorer/TestProjectExplorerSettings.cs
sources/Google.Solutions.IapDesktop.Application.Test/Views/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Services/Settings/ApplicationSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerSettings.cs
sources/Google.Solutions.IapDesktop.Application/Views/ProjectExplorer/ProjectExplorerViewModel.cs

Remove persistence for the OS filter in the Project Explorer window. This behavior is more consistent with how the instance name filter works, and ensures that all instances are shown again when the application is restarted.

b/274055916 Don't persist operating system filter

---

sources/Google.Solutions.IapDesktop/OAuthClient.cs.default
sources/Google.Solutions.IapDesktop/Program.cs

Use main namespace instead of the legacy "CloudIap" namespace

b/278635927 Move OAuth client to main namespace

---

sources/Google.Solutions.IapDesktop.Application.Test/ObjectModel/TestServiceAttribute.cs
sources/Google.Solutions.IapDesktop.Application/ObjectModel/ServiceAttribute.cs
sources/Google.Solutions.IapDesktop.Application/ObjectModel/ServiceRegistry.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Settings/SshSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Services/Settings/TerminalSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Options/SshOptionsSheet.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Options/SshOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Options/TerminalOptionsSheet.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Options/TerminalOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/Session/SessionBroker.cs
sources/Google.Solutions.IapDesktop/Program.cs

Use a common layer for main classes and application. The separation in now redundant to DLL separation, and caused unnecessary friction.

b/279510055 Load extensions into main layer

---

sources/Google.Solutions.Mvvm/Controls/NotificationBarPanel.cs

This avoids an InvalidOperationException when the panel is placed on an AutoHide tool window and its size of creation is (0, 0).
Also, ensure that the label is at fixed position,

b/271356233 Set orientation and label position in OnLayout

---

sources/Google.Solutions.Apis.Test/Client/TestRequestExtensions.cs
sources/Google.Solutions.Apis.Test/Google.Solutions.Apis.Test.csproj
sources/Google.Solutions.Apis.Test/packages.config
sources/Google.Solutions.Apis/Client/RequestExtensions.cs

When an operation fails with a status such as CONDITION_NOT_MET, include the error message in the dialog shown to the user.

b/280531854 Include error details from failed operation

---

sources/Google.Solutions.IapDesktop.Application/Views/Authorization/AuthorizeView.Designer.cs
sources/Google.Solutions.IapDesktop.Application/Views/Authorization/AuthorizeView.cs

Use the product icon when the Authorize dialog
is shown in Alt+Tab or the taskbar preview.

b/280944842 Set icon for Authorize dialog

---

sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopView.cs

After minimizing and restoring a fullscreen view, we receive a bogus resize event. If that happens, skip rearranging control.
This fixes a regression introduced in 7105dd60.

b/280783689 Skip rearranging controls when restoring fullscreen

---

sources/Google.Solutions.IapDesktop.Application.Test/Views/Options/TestGeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/GeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Views/Options/OptionsDialog.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.Platform.Test/Google.Solutions.Platform.Test.csproj
sources/Google.Solutions.Platform.Test/Net/TestBrowserProtocolRegistry.cs
sources/Google.Solutions.Platform/Google.Solutions.Platform.csproj
sources/Google.Solutions.Platform/Net/BrowserProtocolRegistry.cs

Rename AppProtocolRegistry to BrowserProtocolRegistry to disambiguate
custom browser protocols from IAP Desktop's own "app protocols"

b/265601343 Rename to BrowserProtocolRegistry

---

dependencies/makefile
dependencies/sources/tsc/Google.Solutions.Tsc.csproj
dependencies/sources/tsc/Google.Solutions.Tsc.sln
dependencies/sources/tsc/MsRdpClient.cs
dependencies/sources/tsc/Properties/AssemblyInfo.cs
dependencies/sources/tsc/makefile

Building the interop assemblies works poorly with SDK-style projects and
requires Windows Server with Desktop Experience. Extract into separate project
to remove these constraints from the main solution.

b/271897730 Create separate nuget package for TSC interop assemblies

---

sources/Google.Solutions.IapDesktop.Application/Views/Options/NetworkOptionsSheet.Designer.cs

Set minimum bound back to 2, which used to be the limit before it was accidentally increased to 7 in #873.

b/284050594 Fix lower bound for connection limit-control (port from release/2.6)

---

sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Transport/Policies/TestChildProcessPolicy.cs
sources/Google.Solutions.IapDesktop.Core.Test/Google.Solutions.IapDesktop.Core.Test.csproj
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/Policies/ChildProcessPolicy.cs
sources/Google.Solutions.IapDesktop.Core/Google.Solutions.IapDesktop.Core.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.Platform.Test/Dispatch/TestWin32ChildProcessFactory.cs
sources/Google.Solutions.Platform.Test/Dispatch/TestWin32Job.cs
sources/Google.Solutions.Platform.Test/Dispatch/TestWin32ProcessFactory.cs
sources/Google.Solutions.Platform.Test/Google.Solutions.Platform.Test.csproj
sources/Google.Solutions.Platform/Dispatch/IWin32ProcessSet.cs
sources/Google.Solutions.Platform/Dispatch/Win32ChildProcessFactory.cs
sources/Google.Solutions.Platform/Dispatch/Win32Job.cs
sources/Google.Solutions.Platform/Dispatch/Win32JobCollection.cs
sources/Google.Solutions.Platform/Dispatch/Win32ProcessFactory.cs
sources/Google.Solutions.Platform/Google.Solutions.Platform.csproj

Use a dedicated job for each child process launched to work around
the limitations imposed by CreateProcessAsUser.

b/285957479 Use multiple jobs to track child processes

---

sources/Google.Solutions.Common.Test/Format/TestBsdChecksum.cs
sources/Google.Solutions.Common.Test/Google.Solutions.Common.Test.csproj
sources/Google.Solutions.Common/Format/BsdChecksum.cs
sources/Google.Solutions.Common/Google.Solutions.Common.csproj
sources/Google.Solutions.Iap.Test/Google.Solutions.Iap.Test.csproj
sources/Google.Solutions.Iap.Test/Net/TestPortFinder.cs
sources/Google.Solutions.Iap.Test/Util/WebSocketServer.cs
sources/Google.Solutions.Iap/IapListener.cs
sources/Google.Solutions.Iap/Net/PortFinder.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/IapTunnel.cs

Whenever possible, use the same port number every time a tunnel
to the same destination is created. This helps avoid polluting the
history in client applications and take advantage of saved credentials.

b/285787664 Use deterministic port number if possible

---

sources/Google.Solutions.IapDesktop.Application/Views/About/AboutView.cs
sources/Google.Solutions.IapDesktop/Program.cs
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs
sources/Google.Solutions.Mvvm/Binding/PropertiesView.cs
sources/Google.Solutions.Mvvm/Controls/CompositeForm.cs
sources/Google.Solutions.Mvvm/Interop/WindowStyles.cs

Reduce flickering by using composite drawing for top-level windows.
The effects are particularly noticable in dark mode.

Use composite drawing for top-level windows

---

sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

Using WS_EX_COMPOSITED interferes with TSC.

b/286941354 Use non-composite window style for main window

---

sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolClient.cs
sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolContext.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/AppProtocolParameters.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolClient.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolContext.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/App/TestAppContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/App/TestSsmsClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Rdp/TestRdpContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Rdp/TestSessionContextFactoryForRdp.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestSessionContextFactoryForSsh.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestSshContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestConnectionSettingsService.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/App/TestOpenWithAppCommand.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/AppContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/SsmsClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextBase.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/SshContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettingsService.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/AppCommands.cs
sources/Google.Solutions.Testing.Apis/Integration/InstanceAttribute.cs

* Add `AppUsername` setting to connection settings
* Change AppProtolContext to use parameters object
* Use `AppUsername` for SQL Server auth

b/286161182 Allow custom usernames for SQL Server auth

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestCredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/UsernameDialog.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs

* Rename category to "SQL Server" as SSMS is currently the only client that the settings apply to
* Hide username setting as persisted usernames might be confusing when there are multiple client apps
* Fix length of label in username dialog so that the entire protocol name is displayed

b/289861037 Change display of app settings

---

sources/installer/LogsReadme.txt
sources/installer/Product.wxs

* Add component for creating a logs folder
* Simplify .wxs file structure
Creating the logs folder during installation ensures that users never have to create it manually. Creating a folder manually used to be necessary when enabling network tracing.

b/285796905 Create logs folder during installation

---

sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolConfigurationFile.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolConfigurationFile.cs
sources/Google.Solutions.Testing.Apis/Assert.cs

When a file contains syntax errors, show an error message that includes the name of the offending file.

b/289962760 Include file name in error message

---

sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Protocol/TestAppProtocolConfigurationFileSection.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Protocol/AppProtocolConfigurationFile.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Properties/Config/chrome-8080.iapc
sources/Google.Solutions.Platform.Test/TestUserEnvironment.cs
sources/Google.Solutions.Platform/Net/Browser.cs
sources/Google.Solutions.Platform/UserEnvironment.cs

* Add helper method to resolve registered apps using `App Paths` registry key
* Allow the executable in client protocol configuration files to refer to registered apps
* Use the mechanism for Chrome so that it works for 32-bit and 64-bit installs

b/290481676 Automatically resolve path if client executable is a registered app

---

sources/Google.Solutions.IapDesktop.Application/Windows/WaitDialog.cs

When cancalling the wait dialog that's shown during exit, it's possible that the task completes before it can be cancelled.

b/291170927 Fix InvalidOperationException when cancelling wait

---

sources/Google.Solutions.IapDesktop.Application/Windows/ViewBindingContext.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/IapTransportFactory.cs

It's not necessary to enable the IAP API, update error message to reflect this.

b/292444622 Fix error message for missing IAP role

---

sources/Google.Solutions.Apis.Test/Auth/Gaia/TestGaiaOidcClient.cs
sources/Google.Solutions.Apis/Auth/Gaia/GaiaOidcClient.cs
sources/Google.Solutions.Apis/Auth/Gaia/GaiaPkceOidcClient.cs
sources/Google.Solutions.Apis/Client/ApiClientBase.cs
sources/Google.Solutions.Apis/Client/PscAndMtlsAwareHttpClientFactory.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/Authorization/TestAuthorizeViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Authorization/AuthorizeViewModel.cs

Use HttpClientFactory to set user agent so that it's consistently applied across all clients, including the OIDC client.

b/293968777 Set user agent in token requests

---

sources/Google.Solutions.IapDesktop.Extensions.Management.Test/Auditing/Events/Lifecycle/TestInsertInstanceEvent.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/Auditing/Events/Lifecycle/InsertInstanceEvent.cs

This fixes an issue where the usage of an image view caused the event parsing to fail. Remove property as it isn't used anymore.

b/292444274 Remove InsertInstanceEvent.Image property

---

doc/site/sources/docs/proxy-configuration.md
doc/site/sources/docs/security.md

IAP Desktop uses the STS API for workforce identity-based authentication.

b/294784810 Add STS API to list of APIs that might need allow-listing

---

sources/Google.Solutions.IapDesktop.Application.Test/Host/Diagnostics/TestTelemetryListener.cs
sources/Google.Solutions.IapDesktop.Application.Test/Windows/TestMenuCommandAttribute.cs
sources/Google.Solutions.IapDesktop.Application/ApplicationEventSource.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.cs
sources/Google.Solutions.IapDesktop.Application/Windows/MenuCommandBase.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ViewBindingContext.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceControlCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/OpenWithClientCommand.cs
sources/Google.Solutions.Mvvm/Binding/Commands/CommandBase.cs
sources/Google.Solutions.Mvvm/Binding/Commands/ContextCommand.cs
sources/Google.Solutions.Mvvm/Binding/Commands/ICommand.cs
sources/Google.Solutions.Mvvm/Binding/Commands/ObservableCommand.cs

* Add an (optional) ID to commands and use this in ETW traces.
* Embed type/context information in ID where appropriate.

b/298138274 Use ID for tracing command execution

---

sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Transport/TestDirectTransportFactory.cs
sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Transport/TestIapTransportFactory.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/DirectTransportFactory.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/ITransport.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/IapTransportFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/App/TestSsmsClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Rdp/IapTransport.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/App/SsmsClient.cs

Pass the target VM's internal DNS name as "instance name"
to SSMS so that the VM can be identified more easily
in Object Explorer.
Ref #1071

b/292462051 Pass VM name as hint to SSMS

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Ssh/SshTerminalViewModel.cs
sources/Google.Solutions.Ssh.Test/Cryptography/TestRsaSshKeyPair.cs
sources/Google.Solutions.Ssh.Test/Google.Solutions.Ssh.Test.csproj
sources/Google.Solutions.Ssh/Cryptography/AuthenticationChallenge.cs
sources/Google.Solutions.Ssh/Cryptography/ECDsaSshKeyPair.cs
sources/Google.Solutions.Ssh/Cryptography/ISshKeyPair.cs
sources/Google.Solutions.Ssh/Cryptography/RsaSshKeyPair.cs
sources/Google.Solutions.Ssh/Google.Solutions.Ssh.csproj
sources/Google.Solutions.Ssh/Native/SshConnectedSession.cs

* Upgrade to libssh2 1.11 (which added support for rsa-sha2-256 and rsa-sha2-512)
* Handle RFC 8332-style algorithm updates where we authenticate using an ssh-rsa
key but are subsequently challenged for an rsa-sha2-256 or rsa-sha2-512 signature

b/285032643 Support rsa-sha2-256 and rsa-sha2-512 

---

sources/Google.Solutions.IapDesktop.Application/Windows/ViewBindingContext.cs
sources/Google.Solutions.Mvvm.Test/Binding/Commands/TestCommandBindingExtensions.cs
sources/Google.Solutions.Mvvm.Test/Binding/Commands/TestCommandContainer.cs
sources/Google.Solutions.Mvvm/Binding/BindingContext.cs
sources/Google.Solutions.Mvvm/Binding/Commands/CommandBindingExtensions.Generated.cs
sources/Google.Solutions.Mvvm/Binding/Commands/CommandBindingExtensions.Generated.tt
sources/Google.Solutions.Mvvm/Binding/Commands/CommandContainer.cs

Use the control's window as parent if possible. This fixes an issue where error dialogs triggered by the Options dialog were parented to the main window, not the Options dialog.

b/296956322 Fix parenting of error dialog

---

sources/Google.Solutions.Iap/IapListener.cs

Nagle's algorithm isn't needed, but can possibly lead to undesired relaying delays.

b/304140852 Disable Nagle's algorithm for relay

---

sources/Google.Solutions.Apis/Auth/Gaia/GaiaOidcSession.cs

Logs Viewer URLs contain quotes, which is something ServiceLogin cannot handle.

b/304382646 Skip ServiceLogin for Logs Viewer URLs

---

sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeView.cs
sources/Google.Solutions.IapDesktop.Application/Windows/ViewBindingContext.cs
sources/Google.Solutions.IapDesktop/Properties/launchSettings.json
sources/Google.Solutions.IapDesktop/Windows/MainForm.cs

When no handle is provided, use the process main window handle as parent for error dialogs. This fixes an issue where the authorize dialog, after a reauth, registered itself as the default error window parent but was subsequently disposed.

b/304584429 Fall back to using process main window handle as parent

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Options/TestGeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Host/Install.cs
sources/Google.Solutions.IapDesktop.Application/Theme/VSThemeExtensions.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Auth/AuthorizeViewModel.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Options/GeneralOptionsViewModel.cs
sources/Google.Solutions.IapDesktop/Windows/MainFormViewModel.cs

When a float window is split, the library resets
the icon and sets the title to " ".
When that happens, apply the standard title and
icon again so that we avoid showing a windows with a standard icon and empty title.

b/304847158 Apply standard title, icon when splitting float window

---

sources/Google.Solutions.IapDesktop.Extensions.Diagnostics/Google.Solutions.IapDesktop.Extensions.Diagnostics.csproj
sources/Google.Solutions.IapDesktop.Extensions.Management/Google.Solutions.IapDesktop.Extensions.Management.csproj
sources/Google.Solutions.IapDesktop.Extensions.Session/Google.Solutions.IapDesktop.Extensions.Session.csproj
sources/Google.Solutions.IapDesktop/Google.Solutions.IapDesktop.csproj

Using a post-build copy operation is providing to be unreliable, so use a project reference to force extension DLLs (and their dependencies) to be copied to the main output folder.

Add project references to Extension DLLs

---

sources/Google.Solutions.Apis.Test/Compute/TestOsLoginClient.cs
sources/Google.Solutions.Apis/Compute/OsLoginClient.cs
sources/Google.Solutions.Apis/HelpTopics.cs

Extend OsLoginClient to expose selected v1beta1 methods. Use inline request/response classes to avoid having to juggle 2 NuGet references

b/308213280 Expose v1beta1 methods in OsLoginClient

---

sources/Google.Solutions.Apis.Test/Compute/TestComputeEngineClient.cs
sources/Google.Solutions.Apis.Test/Crm/TestResourceManagerClient.cs
sources/Google.Solutions.Apis/Compute/ComputeEngineClient.cs
sources/Google.Solutions.Apis/Compute/IComputeEngineClient.cs
sources/Google.Solutions.Apis/Compute/Permissions.cs
sources/Google.Solutions.Apis/Compute/WindowsCredentialGenerator.cs
sources/Google.Solutions.Apis/Crm/ResourceManagerClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestInstanceMetadataAuthorizedPublicKeyProcessor.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/MetadataAuthorizedPublicKeyProcessor.cs

* Verify that the user has the `iam.serviceAccounts.actAs` permission on the project before pushing to project metadata
* Fall back to instance metadata if permission is not held

b/309373652 Avoid pushing SSH key to project metadata if ActAs permission missing

---

sources/Google.Solutions.IapDesktop.Application.Test/Host/Diagnostics/TestBugReport.cs
sources/Google.Solutions.IapDesktop.Application/Host/Diagnostics/BugReport.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/ExceptionDialog.cs

Include the name and type of source window and
control, if known. This is to assist finding the source of unhandled exceptions.

b/304359886 Include window details in bug report

---

sources/makefile

Remove installer/bin folder from snapshot to force the sign job to rebuild the MSI.

Force sign job to rebuild MSI

---

sources/Google.Solutions.Iap.Test/Protocol/Mocks.cs
sources/Google.Solutions.Iap.Test/Protocol/TestSshRelayStream.SocketHandling.cs
sources/Google.Solutions.Iap/IapListener.cs
sources/Google.Solutions.Iap/Net/PortFinder.cs
sources/Google.Solutions.Iap/Protocol/SshRelaySession.cs
sources/Google.Solutions.IapDesktop.Core.Test/ClientModel/Transport/TestIapTunnel.cs
sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/IapTunnel.cs

When a dynamically allocated port can't be used because of a persistent port reservation, allocate a different port and try again.

b/309816619 Handle dynamic port reservations conflicts

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Rdp/TestWindowsUser.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/WindowsUser.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Credentials/CreateCredentialsWorkflow.cs

When the connection settings contain a UPN, avoid
using that UPN as suggested username.

b/291167569 Don't use UPN for generating a local Windows user

---

sources/Google.Solutions.Mvvm/Theme/SystemTheme.cs

ShouldAppsUseDarkMode returns a 1-byte boolean, not a 4-byte boolean (BOOL) as Win32 APIs typically do.

b/285779973 Fix ShouldAppsUseDarkMode call on x64

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/App/ConnectAppProtocolCommandBase.cs
sources/Google.Solutions.Platform.Test/Dispatch/TestWin32ChildProcessFactory.cs
sources/Google.Solutions.Platform.Test/Dispatch/TestWin32Job.cs
sources/Google.Solutions.Platform.Test/Dispatch/TestWin32ProcessFactory.cs
sources/Google.Solutions.Platform/Dispatch/Win32ChildProcessFactory.cs
sources/Google.Solutions.Platform/Dispatch/Win32Job.cs
sources/Google.Solutions.Platform/Dispatch/Win32Process.cs
sources/Google.Solutions.Platform/Dispatch/Win32ProcessFactory.cs

When launching a client app, wait for all its child processes to terminate before tearing down the tunnel.

b/314874064 Wait for descendent processes before closing tunnel

---

sources/Google.Solutions.Mvvm/Binding/Commands/CommandContainer.cs

When the context is null, we have to assume that all commands are unavailable. Hiding all menu items looks awkward though, so disable them.

b/322255942 Disable, but don't hide commands if context is null

---

sources/build.ps1

Using a custom packageSourceMapping isn't needed anymore as all private packages use a reserved prefix now.

b/324318081 Use standard nuget.config

---

sources/Google.Solutions.Mvvm/Controls/FileBrowser.cs

This fixes a spuriuous source of NullReferenceExceptions.

b/325757513 Ignore double-clicks when no file selected

---

sources/Google.Solutions.Apis.Test/Compute/TestOsLoginClient.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestPlatformCredentialAuthentication.cs

Update tests to reflect latest API changes:
* Re-enable WFIF/OSLogin tests
* Change test to expect SignSshPublicKey to succeed when using Gaia credentials

b/325545018 Re-enable tests affected by b/325544415

---

sources/Google.Solutions.IapDesktop.Application/ToolWindows/Properties/SettingsCollectionTypeDescriptor.cs
sources/Google.Solutions.Settings.Test/ComponentModel/TestMaskedSettingDescriptor.cs
sources/Google.Solutions.Settings.Test/ComponentModel/TestSettingDescriptor.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfBool.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfEnum.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfEnumFlags.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfInt.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfLong.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfSecureString.cs
sources/Google.Solutions.Settings.Test/RegistrySettingsStoreOfString.cs
sources/Google.Solutions.Settings/ComponentModel/MaskedSettingDescriptor.cs
sources/Google.Solutions.Settings/ComponentModel/SettingDescriptor.cs
sources/Google.Solutions.Settings/ISetting.cs

* Move SettingDescriptor implementations to Settings assembly
* Make IAnySetting internal so that all usage of settings outside of the Settings assembly is strongly-typed

b/330223655 Turn IAnySetting into internal interface

---

sources/Google.Solutions.Apis/Auth/Iam/AuthPortalCodeFlow.cs
sources/Google.Solutions.IapDesktop/Properties/launchSettings.json

Previous versions of the oauthtoken endpoint ignored client credentials that were passed as POST parameter and only considered credentials passed as Basic auth header.
This recently changed and passing a "client_secret" POST- parameter now causes the server to reject the request.
Change client implementation to only send credentials as Basic auth header and remove the respective POST parameters.

b/331674228 Remove client credentials from POST paramaters

---

sources/Google.Solutions.Apis/Compute/ComputeEngineClient.cs

Ignore zones or regions that are currently unavailable, cf. go/drd-cp.

b/333293555 Allow partial success for AggregatedList calls

---

sources/Google.Solutions.IapDesktop/App.config
sources/installer/Product.wxs

Check for Windows 10 1607 as minimum version, which is the first version to support .NET 4.7.

b/335741487 Refine minimum version requirement

---

sources/Google.Solutions.Ssh.Test/Native/TestLibssh2AuthenticatedSession.cs
sources/Google.Solutions.Ssh.Test/Native/TestLibssh2Session.cs
sources/Google.Solutions.Ssh/Native/Libssh2ConnectedSession.cs
sources/Google.Solutions.Ssh/Native/Libssh2Session.cs
sources/Google.Solutions.Ssh/Native/NativeMethods.cs
sources/Google.Solutions.Ssh/SshWorkerThread.cs

When using the WinCNG backend, key exchanges can occasionally fail,
see https://github.com/libssh2/libssh2/issues/804.

b/335741487 Retry session initialization when key exchange fails

---

README.md
doc/site/sources/docs/index.md
doc/site/sources/mkdocs.yml

Change links in README and docs to download x64 installer by default

b/337703105 Download x64 installer by default

---

sources/Google.Solutions.Common.Test/Runtime/TestInstanceActivator.cs
sources/Google.Solutions.Common/Runtime/IActivator.cs
sources/Google.Solutions.Common/Runtime/InstanceActivator.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/InputDialog.cs
sources/Google.Solutions.IapDesktop.Core.Test/ObjectModel/TestService.cs
sources/Google.Solutions.IapDesktop.Core.Test/ObjectModel/TestServiceRegistry.cs
sources/Google.Solutions.IapDesktop.Core/ObjectModel/Service.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/GuestOs/ActiveDirectory/DomainJoinService.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/EventLog/EventLogViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/InstanceProperties/InstancePropertiesInspectorViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/PackageInventory/PackageInventoryViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Management/ToolWindows/SerialOutput/SerialOutputViewModel.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/SshKeys/AuthorizedPublicKeysViewModel.cs
sources/Google.Solutions.Mvvm/Binding/WindowActivator.cs

Rename method Activate, which is neutral w.r.t.
whether it creates a new instance or reuses an
existing instance.

b/341201732 Rename to IActivator.Activate()

---

sources/Google.Solutions.IapDesktop.Application/Theme/VSThemeRuleSet.cs
sources/Google.Solutions.Mvvm/Controls/CompositeForm.cs
sources/Google.Solutions.Mvvm/Theme/DeviceCapabilities.cs
sources/Google.Solutions.Mvvm/Theme/GdiScalingRuleset.cs

Check if GDI scaling is actually in use before disabling double-buffering. This improves rendering performance in dark mode on systems that use the default DPI.

b/341834296 Use double buffering when GDI scaling not active

---

dependencies/sources/dockpanelsuite/makefile
dependencies/sources/dockpanelsuite/patches/0004-Target-.NET-4.7.patch
dependencies/sources/dockpanelsuite/patches/0005-Scale-control-buttons-to-device-units.patch

Apply two patches to DockPanelSuite:
* Target .NET 4.7
* Scale control buttons to device units

b/342523478 Add patches for scaling control buttons

---

sources/Google.Solutions.IapDesktop.Application/Windows/ProjectPicker/ProjectPickerView.Designer.cs
sources/Google.Solutions.Mvvm/Controls/DpiAwareUserControl.cs
sources/Google.Solutions.Mvvm/Controls/SearchableList.cs
sources/Google.Solutions.Mvvm/Theme/DpiAwarenessRuleset.cs

When a UserControl has been parented and we're in High-DPI mode. Winforms
autoscales the UserControl and _should_ resize any nested controls
that are anchored to scale horizontaly or vertically. But that doesn't
happen due to issue 6381.
As a workaround, we look for affected controls and resize them explicitly.

b/342952290 Add mitigation for user controls anchoring bug in NetFx

---

dependencies/sources/dockpanelsuite/makefile

Include tag to force Windows Installer to replace existing/ older versions of the file.
This is to address b/359613390, b/360704492, b/360802226

b/360927073 Include tag in DockPanelSuite file versions

---

sources/Google.Solutions.IapDesktop/app.manifest

Add manifest entry to force the use of comctl32 6.0 across the application. Previously, the application loaded both 6.0 and a downlevel version -- which is unnecessary and a potential source of linking issues.

b/346148567 Force usage of comctl32 6.0

---

sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/ProjectExplorer/TestProjectExplorerViewModelNodes.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerViewModel.Nodes.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Core/ProjectModel/ProjectWorkspace.cs

- Split files
- When updating node states, only consider loaded nodes and avoid triggering a load

b/341175020 Refactor Explorer view model

---

sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Core.Test/ObjectModel/TestEventQueue.cs
sources/Google.Solutions.IapDesktop.Core/ObjectModel/EventQueue.cs
sources/Google.Solutions.IapDesktop.Core/ObjectModel/IEventQueue.cs

Extend `EventQueue` to support weak subscriptions that avoid keeping the subsribing object alive.

b/372091044 Weak EventQueue subscriptions

---

sources/Google.Solutions.Platform.Test/Dispatch/TestWin32ProcessFactory.cs
sources/Google.Solutions.Platform.Test/Dispatch/TestWin32PseudoConsole.cs
sources/Google.Solutions.Platform.Test/IO/TestPseudoTerminaSize.cs
sources/Google.Solutions.Platform.Test/IO/TestPseudoTerminalException.cs
sources/Google.Solutions.Platform/Dispatch/IWin32Process.cs
sources/Google.Solutions.Platform/Dispatch/Win32Process.cs
sources/Google.Solutions.Platform/Dispatch/Win32ProcessFactory.cs
sources/Google.Solutions.Platform/Dispatch/Win32PseudoConsole.cs
sources/Google.Solutions.Platform/IO/IPseudoTerminal.cs
sources/Google.Solutions.Platform/IO/PseudoTerminalException.cs
sources/Google.Solutions.Platform/IO/PseudoTerminalExtensions.cs
sources/Google.Solutions.Terminal.Test/Controls/TestTerminalDeviceBinding.cs
sources/Google.Solutions.Terminal.Test/Controls/TestVirtualTerminal.cs
sources/Google.Solutions.Terminal.TestApp/Program.cs
sources/Google.Solutions.Terminal/Controls/TerminalBinding.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Use term 'pseudo-terminal' instead of 'pseudo-console' as the latter is Windows-specific

b/345335944 Rename interface to IPseudoTerminal

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Session/TestSessionCommands.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/InitializeSessionExtension.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/IRdpSession.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/SessionCommands.cs
sources/Google.Solutions.Terminal.Test/Controls/TestRdpClient.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.cs

Add 'Sign out' command to Session menu. There's no API to log off a user programatically, so the command makes a "best effort" to initiate a logoff by using the security screen. This works reliably on Windows client and Windows Server with Desktop experience, but not on Server Core.
ref #1463.

b/372352359 Add command to sign out of RDP session

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Rdp/TestRdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Rdp/TestRdpView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session.Test/ToolWindows/Session/TestRdpCredentialEditor.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/RdpCredentialEditor.cs

Extend the existing `RdpUserAuthenticationBehavior` setting so that it can be used to control automatic logons.
If automatic logons are enabled (the default), IAP Desktop attempts to use save credentials, or will prompt the user to enter or generate new credentials if necessary.
If automatic logons are disabled, IAP Desktop ignores saved credentials and defers all prompting to the RDP control. This behavior ensures compliance with the _Always prompt for password upon connection_ server-side group policy.
ref #1501

b/372783667 Control automatic logons

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.Settings.Test/ComponentModel/TestEnumDisplayNameConverter.cs
sources/Google.Solutions.Settings.Test/ComponentModel/TestSettingDescriptor.cs
sources/Google.Solutions.Settings/ComponentModel/EnumDisplayNameConverter.cs
sources/Google.Solutions.Settings/ComponentModel/SettingDescriptor.cs

- Use TypeConverter to expose descriptions (instead of member names) for enum-types properties
- Annotate connection setting enums
- Hide Server authentication level setting as it's not useful in IAP scenarios

v/372787399 Expose enum descriptions in properties window

---

sources/Google.Solutions.Settings.Test/ComponentModel/TestMaskedSettingDescriptor.cs
sources/Google.Solutions.Settings/ComponentModel/MaskedSettingDescriptor.cs

- Show masked value instead of an empty value if the setting is inherited
- Reflect original length

b/354037219 Show masked value for inherited SecureString settings

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Settings/TestConnectionSettingsRepository.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Rdp/RdpParameters.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/SessionContextFactory.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Rdp/RdpView.cs
sources/Google.Solutions.Terminal.Test/Controls/TestRdpClient.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.ConnectionProperties.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.cs

- Restore `ScreenSize` connection setting.
- Extend `RdpClient` to adjust remote desktop size and disable automatic resizing based on connection setting.
Ref #1461

b/372783332 Restore conection setting for controlling remote desktop size

---

sources/Google.Solutions.Terminal.Test/Controls/TestPseudoTerminalClientBase.cs
sources/Google.Solutions.Terminal/Controls/LocalShellClient.cs
sources/Google.Solutions.Terminal/Controls/PseudoTerminalClientBase.cs

Allow async implementations because some connections (such as slow) are slow to establish.

b/335313274 Convert ConnectCore to async method

---

sources/Google.Solutions.IapDesktop.Application.Test/Windows/Dialog/TestCredentialDialog.cs
sources/Google.Solutions.IapDesktop.Application/Windows/Dialog/CredentialDialog.cs

Incorporate domain into username when packing credential. This ensures that when CredUI shows the credential prompt, it defaults to the user-specified domain as opposed to the local computer's domain.

b/371112522 Include domain in packed credential

---

sources/Google.Solutions.Terminal/Controls/ClientBase.cs
sources/Google.Solutions.Terminal/Controls/ClientDiagnosticsWindow.cs
sources/Google.Solutions.Terminal/Controls/RdpClient.cs

- Use IsContainerFullScreen instead of IsFullScreen to determine the connection state because IsFullScreen doesn't immediately reflect the correct value after leaving full-screen mode.
- This fixes an issue where an RDP client was left in a defunct state after the session timed out in full-screen mode.

b/374823115 Use IsContainerFullScreen for state tracking

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestMetadataAuthorizedPublicKey.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/IAuthorizedPublicKey.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/MetadataAuthorizedPublicKey.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/SshKeys/AuthorizedPublicKeysList.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/SshKeys/AuthorizedPublicKeysViewModel.cs

- Relax parsing rules to allow excess whitespace
- Refactor tests

Relax parsing rules for metadata keys

---

sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Previous logic doesn't seem necessary, and it caused TAB events to be processed incorrectly.

b/375965264 Remove logic for synthetic keydown events

---

sources/Google.Solutions.Mvvm.Test/Shell/TestFileDataObject.cs
sources/Google.Solutions.Mvvm/Shell/FileDataObject.cs

Add DataObject implementation that supports clipboard operations
comprising multiple virtual files.

b/376134352 Add DataObject for multi-file clipboard operations

---

sources/Google.Solutions.Common.Test/IO/TestStreamExtensions.cs
sources/Google.Solutions.Common/IO/StreamExtensions.cs
sources/Google.Solutions.Ssh.Test/TestSshFileSystemChannel.cs
sources/Google.Solutions.Ssh/FilePermissions.cs
sources/Google.Solutions.Ssh/Native/NativeMethods.cs
sources/Google.Solutions.Ssh/SshConnection.cs
sources/Google.Solutions.Ssh/SshFileStream.cs
sources/Google.Solutions.Ssh/SshFileSystemChannel.cs

- Extend `SshFileSystemChannel` to return a `Stream` when creating or opening a file
- Add `Stream` implementation that reads or writes via SFTP
- Add `CopyToAsync` extension method

b/376134352 Access SFTP file as stream

---

sources/Google.Solutions.IapDesktop.Application/Theme/VSThemeRuleSet.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.Designer.cs
sources/Google.Solutions.Mvvm/Theme/WindowsRuleSet.cs

Disable borders for a "flatter" view. This also prevents the thick border
around the tree view after opening the file browser in dark mode.

b/376156037 Disable borders around list views, tree views

---

sources/Google.Solutions.IapDesktop.Application/Theme/VSThemeRuleSet.cs
sources/Google.Solutions.Mvvm/Controls/NotificationBarPanel.cs

Use a backcolor that differs from other container controls to ensure that the splitter is visible.

b/380168415 Use different backcolor for splitter

---

sources/Google.Solutions.Mvvm.Test/Controls/TestOperationProgressDialog.cs
sources/Google.Solutions.Mvvm/Controls/FileBrowser.cs
sources/Google.Solutions.Mvvm/Controls/OperationProgressDialog.cs

When a file copy error occiurs block the operation dialog while showing an error message.

b/380931103 Pause operation dialog when showing error

---

sources/Google.Solutions.Mvvm.Test/Controls/TestFileBrowser.cs
sources/Google.Solutions.Mvvm/Controls/FileBrowser.cs
sources/Google.Solutions.Ssh/SshConnection.cs
sources/Google.Solutions.Ssh/SshException.cs
sources/Google.Solutions.Ssh/SshWorkerThread.cs

- Cancel pending send operations
- Handle cancellation in UI
This fixes an issue where closing an SSH terminal causes pending I/O tasks to hang, and the operation progress dialog of uploads to become stuck.

b/380752047 Cancel file uploads when SSH session closed

---

sources/Google.Solutions.IapDesktop/Program.cs

Call SetCompatibleTextRenderingDefault earlier
during initialization to minimze the risk
that any window is created before.

b/380896840 Move SetCompatibleTextRenderingDefault call

---

sources/installer/Product.wxs

Mark `WINDOWS_CURRENTBUILDNUMBER` property as secure, otherwise
it might not be passed to the execute sequence for certain users (depending
on machine policies and elevation state), causing the launch condition to fail.
Re #1580

b/382116424 Use secure property for Windows build number 

---

sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/ConnectionSettings.cs
sources/Google.Solutions.IapDesktop.Extensions.Session/Settings/LocalRdpPolicy.cs

Vary the default based on the local `DisablePasswordSaving` policy. When this policy is enforced, disable automatic logons to reduce the potenial for redundant password prompts.

b/376106075 Vary default for automatic logon based on group policy

---

sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Make sure the flag to ignore WM_CHAR message is reset after the next WM_CHAR message has been processed. This fixes an issue where in certain situations, WM_CHAR messages continue to be ignored, causing the terminal to become unresponsive.

b/383645831 Fix WM_CHAR handling during accelerator handling

---

sources/Google.Solutions.IapDesktop.Extensions.Session/ToolWindows/Session/RdpView.cs

Always use existing credentials, even if automatic logons are disabled. This upholds the spririt of the automatic logon setting, but reduces impact for (pre-2.44) users who have existing credentials and now find themselves to be subject to a group policy that disabled automatic logons.

b/388039767 Use existing password if auto-logon disabled

---

sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerViewModel.Nodes.cs
sources/Google.Solutions.IapDesktop.Core.Test/ProjectModel/TestProjectWorkspace.cs
sources/Google.Solutions.IapDesktop.Core/ProjectModel/ProjectWorkspace.cs

- Avoid proagating ResourceNotFoundExceptions if a project doesn't exist
- Handle ResourceNotFoundExceptions like ResourceAccessDeniedExceptions
- Ensure that the context menu is properly updated for nonexisting projects

b/388188829 Handle nonexisting projects like inaccessible projects

---

dependencies/sources/terminal-icushim/icu.c
dependencies/sources/terminal-icushim/icu.def
dependencies/sources/terminal-icushim/makefile
dependencies/sources/terminal/makefile

* Update `Google.Solutions.ThirdParty.Terminal` to use `microsoft/terminal/releases/tag/v1.21.3231.0`
* Add `utext_close` to ICU Shim to satisfy imports of that version

b/390040853 Update to Terminal 1.21.3231

---

doc/site/sources/docs/keyboard-shortcuts.md

Remove terminal shortcuts that are no longer supported as of release 2.44:
- Shift + Right
- Ctrl + Up/Down
cf #1611

b/392734231 Remove defunct shortcuts

---

sources/Google.Solutions.Platform/Dispatch/Win32PseudoConsole.cs

Fix a situation where the pump enters an endless
loop because the object has been disposed.

b/390040853 Stop pumping pseudo-console events after dispose

---

sources/Google.Solutions.IapDesktop.Application.Test/ToolWindows/ProjectExplorer/TestProjectExplorerViewModel.cs
sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerViewModel.Nodes.cs

- Ignore leading and trailing whitespace in filter term
- Perform a case-insensitive comparison against the VM name

b/392726558 Ignore case, whitespace when filtering VMs

---

sources/Google.Solutions.Mvvm.Test/Interop/TestComStream.cs
sources/Google.Solutions.Mvvm.Test/Shell/TestVirtualFileDataObject.cs
sources/Google.Solutions.Mvvm/Interop/ComStream.cs
sources/Google.Solutions.Mvvm/Shell/VirtualFileDataObject.cs
sources/Google.Solutions.Platform/Interop/Hresult.cs
sources/Google.Solutions.Ssh/SftpFileStream.cs

When downloading a file over SFTP (using drag/drop or copy/paste),
use `TYMED_ISTREAM` instead of `TYMED_HGLOBAL` is possible. 
`TYMED_HGLOBAL` works okay for small files, but requies excessive
memory when downloading large files. Using `TYMED_ISTREAM`
avoids that.
- Add `TYMED_ISTREAM` support to `VirtualFileDataObject` to 
compensate for the missing support in the BCL.
- Add `ComStream` to wrap managed streams as a COM `IStream`

b/392743633 Use TYMED_ISTREAM for file downloads

---

sources/Google.Solutions.Apis/Auth/Gaia/GaiaOidcClient.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

A servicerestricted error isn't necessarily caused by a missing EV enrollment, but can be caused by other CAA requirements not being met.

b/394184904 Show more accurate error message when OAuth exchange fails

---

sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerViewModel.cs

This fixes an issue where opening the authorized keys-view fails when loading the cloud node hasn't completed yet.

b/380753702 Prevent access to selected node while loading

---

sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Ensure proper scrolling behavior in case `MouseWheelScrollLines` returns `-1`.

b/392734231: Scroll by at least 1 line

---

sources/Google.Solutions.Ssh/Native/Libssh2ChannelBase.cs
sources/Google.Solutions.Ssh/SshShellChannel.cs
sources/Google.Solutions.Ssh/SshWorkerThread.cs

When WSAWaitForMultipleEvents indicates that there's data on the shell channel, read as much data as available because the WSA event won't remain signalled.
This fixes an issue where the terminal output can suddenly stall if the server produces output more quickly than the client can read it.

b/397280361 Read all available output on shell channel

---

sources/Google.Solutions.Mvvm/Controls/ClipboardUtil.cs
sources/Google.Solutions.Terminal/Controls/VirtualTerminal.cs

Copy current selection on (left/right) mouse click, unless the selection is all-whitespace.
This aligns the behavior with the Windows terminal.

b/402564632 Copy selection on mouse click

---

sources/Google.Solutions.IapDesktop.Extensions.Session.Test/Protocol/Ssh/TestPlatformCredentialAuthentication.cs

Disabling OS Login-based test because the IAM propagation delay makes it unreliable in CI.

b/409123329 Disabling test

---

sources/Google.Solutions.IapDesktop.Application/ToolWindows/ProjectExplorer/ProjectExplorerView.cs

This fixes an issue where moving the focus to IAP Desktop by double-clicking a Project Explorer node caused the ConnectInstance command to be executed twice -- once for a KeyCode.None and once for a double-click.

b/418214603 Prevent KeyCode.None from triggering defaut command
